Repository AmbireTech/ambire-common, pull requests merged in 2024-09, with the labels that each got.

#981 High gasUsed errors & warnings
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/interfaces/network.ts
  src/libs/gasPrice/gasPrice.ts
  src/libs/gasPrice/tests/1559Network.test.ts
  src/libs/gasPrice/tests/non1559Network.test.ts
Labels: bug

#986 Re-estimate on paymaster error
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#991 Fix: limit 500kk estimation rule to predefined networks
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#992 Enhancement / toBeLearned tokens before LearnedTokens
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/libs/portfolio/helpers.ts
  src/libs/portfolio/portfolio.ts
Labels: bug

#977 Feature / Add Key Timestamp
  src/controllers/emailVault/emailVault.test.ts
  src/controllers/keystore/keystore.test.ts
  src/controllers/keystore/keystore.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signMessage/signMessage.test.ts
  src/interfaces/keyIterator.ts
  src/interfaces/keystore.ts
  src/libs/account/account.test.ts
  src/libs/humanizer/index.test.ts
  src/libs/keyIterator/keyIterator.ts
  src/libs/keys/keys.ts
  src/libs/keystoreSigner/keystoreSigner.test.ts
  src/libs/signMessage/signMessage.test.ts
  test/helpers.ts
Labels: enhancement

#995 Fix: bigint sort problem
  src/libs/portfolio/getOnchainBalances.ts
Labels: bug

#993 Fix 6492 signature
  src/controllers/signMessage/signMessage.ts
Labels: bug

#997 Rename matic to pol
  src/consts/gasTankFeeTokens.ts
  src/consts/networks.ts
  src/controllers/networks/networks.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/transfer/transfer.test.ts
  src/interfaces/network.ts
  src/libs/humanizer/modules/1Inch/1inch.test.ts
  src/libs/portfolio/helpers.ts
Labels: refactoring

#990 Refactor/ Move functions from transfer ctrl to utils
  src/controllers/transfer/transfer.ts
  src/libs/portfolio/interfaces.ts
  src/utils/numbers/formatters.ts
Labels: refactoring

#1000 Fix: do not wrap the AmbireOperation in magic bytes
  src/controllers/signMessage/signMessage.ts
Labels: bug

#994 Add/metamask contract metadata
  package.json
  scripts/updateHumanizerInfoWithMetaMaskContactMetadata.js
  src/consts/humanizer/humanizerInfo.json
Labels: enhancement

#1002 Remove matic zero addr hardcoded symbol
  src/consts/humanizer/humanizerInfo.json
Labels: bug

#979 Remove async ops from humanizer
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/controllers/signMessage/signMessage.test.ts
  src/controllers/signMessage/signMessage.ts
  src/interfaces/humanizer.ts
  src/libs/accountOp/accountOp.ts
  src/libs/humanizer/humanizerFuncs.ts
  src/libs/humanizer/humanizerModules.test.ts
  src/libs/humanizer/index.test.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/interfaces.ts
  src/libs/humanizer/lazyStorage.test.ts
  src/libs/humanizer/lazyStorage.ts
  src/libs/humanizer/modules/1Inch/1inch.test.ts
  src/libs/humanizer/modules/1Inch/index.ts
  src/libs/humanizer/modules/Aave/aave.test.ts
  src/libs/humanizer/modules/Aave/index.ts
  src/libs/humanizer/modules/Across/across.test.ts
  src/libs/humanizer/modules/Across/index.ts
  src/libs/humanizer/modules/Curve/curve.test.ts
  src/libs/humanizer/modules/Curve/index.ts
  src/libs/humanizer/modules/FallbackHumanizer/fallBackHumanizer.ts
  src/libs/humanizer/modules/FallbackHumanizer/fallbackHumanizer.test.ts
  src/libs/humanizer/modules/GasTankModule/gasTank.test.ts
  src/libs/humanizer/modules/GasTankModule/gasTankModule.ts
  src/libs/humanizer/modules/KyberSwap/index.ts
  src/libs/humanizer/modules/KyberSwap/kyberSwap.test.ts
  src/libs/humanizer/modules/PostProcessing/postProcessModule.ts
  src/libs/humanizer/modules/PostProcessing/postProcessing.test.ts
  src/libs/humanizer/modules/PreProcess/preProcessModule.ts
  src/libs/humanizer/modules/Privileges/privileges.test.ts
  src/libs/humanizer/modules/Privileges/privileges.ts
  src/libs/humanizer/modules/Socket/socket.test.ts
  src/libs/humanizer/modules/Socket/socketModules.ts
  src/libs/humanizer/modules/Sushiswap/sushiSwapModule.ts
  src/libs/humanizer/modules/Sushiswap/sushiswap.test.ts
  src/libs/humanizer/modules/Tokens/tokens.test.ts
  src/libs/humanizer/modules/Tokens/tokens.ts
  src/libs/humanizer/modules/TraderJoe/index.ts
  src/libs/humanizer/modules/TraderJoe/traderjoe.test.ts
  src/libs/humanizer/modules/Uniswap/index.ts
  src/libs/humanizer/modules/Uniswap/uniUniversalRouter.ts
  src/libs/humanizer/modules/Uniswap/uniswap.test.ts
  src/libs/humanizer/modules/WALLET/index.ts
  src/libs/humanizer/modules/WALLET/wallet.test.ts
  src/libs/humanizer/modules/Wrapping/wrapping.test.ts
  src/libs/humanizer/modules/Wrapping/wrapping.ts
  src/libs/humanizer/parsers/humanizerMetaParsing.ts
  src/libs/humanizer/typedMessageModules/erc20Module.ts
  src/libs/humanizer/utils.ts
Labels: refactoring

#1001 Refactor: entry point sign message
  src/controllers/signMessage/signMessage.ts
  src/libs/signMessage/signMessage.ts
Labels: refactoring

#1004 Enhancement/ `info2` Banner type
  src/interfaces/banner.ts
Labels: enhancement

#1008 Feature/humanizer enhancements and fixes
  src/libs/humanizer/const/abis/Uniswap.ts
  src/libs/humanizer/modules/Socket/socket.test.ts
  src/libs/humanizer/modules/Socket/socketModules.ts
  src/libs/humanizer/modules/Uniswap/uniV3.ts
  src/libs/humanizer/modules/Uniswap/uniswap.test.ts
Labels: bug, enhancement
