Repository AmbireTech/ambire-common, pull requests merged in 2024-04, with the labels that each got.

#680 Docs/ Domains controller replaced jsdoc with a regular comment
  src/controllers/domains/domains.ts
Labels: documentation

#681 Enhancement: better detection of when the rpc is bad when adding a network
  src/libs/settings/settings.ts
Labels: enhancement

#685 Use static providers
  src/controllers/settings/settings.ts
Labels: enhancement

#683 Fix: nonce discrepancy issues when there's a pending txn
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/estimate/errors.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/interfaces.ts
Labels: bug

#686 Fix silent errors during signAccountOp tests
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/transfer/transfer.test.ts
Labels: bug

#687 Fix/4337 token balances
  contracts/compiled/Estimation.json
  contracts/deployless/Estimation.sol
  contracts/deployless/EstimationStructs.sol
  contracts/deployless/FeeTokens.sol
  contracts/deployless/IERC20Subset.sol
  contracts/deployless/SimulateSigned.sol
  src/controllers/main/main.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.test.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/interfaces.ts
Labels: enhancement

#693 Feature/eoa estimation.sol
  contracts/compiled/Estimation.json
  contracts/deployless/Estimation.sol
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateEOA.ts
  src/libs/estimate/reestimate.ts
Labels: enhancement

#694 Stop: debug trace call for predefined networks | estimateWithRetries | ERC-4337 estimation failure
  src/consts/networks.ts
  src/libs/estimate/errors.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/estimateEOA.ts
  src/libs/estimate/estimateWithRetries.ts
Labels: enhancement

#696 Add: token to payOptions to reduce FE logic complexity
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/calls/calls.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.test.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/estimateEOA.ts
  src/libs/estimate/interfaces.ts
Labels: enhancement

#698 Fix/math rounding bug
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#699 Bug/ Selected token information isn't updated if the token is already selected
  src/controllers/transfer/transfer.ts
Labels: bug

#679 Update/ Pass addressBook ctrl as param to the constructor of Transfer
  src/controllers/main/main.ts
  src/controllers/transfer/transfer.test.ts
  src/controllers/transfer/transfer.ts
  src/interfaces/transfer.ts
Labels: enhancement

#701 Bug/ Missing initial value for selectedAccount (addressBook)
  src/controllers/main/main.ts
Labels: bug

#704 Fix: remove token icon fetching from portfolio
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/libs/portfolio/icons.ts
  src/libs/portfolio/interfaces.ts
Labels: bug

#708 Fix: improve 4337 dapp feedback
  src/controllers/transfer/transfer.test.ts
  src/services/bundlers/bundler.ts
Labels: bug

#709 Fix: native fee payment option for custom network first SA txn
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
Labels: bug

#710 Bug/ Portfolio lib swallows `priceIn` errors
  src/controllers/portfolio/portfolio.ts
  src/libs/banners/banners.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.ts
Labels: bug

#702 Refactor/fee speeds
  src/controllers/main/main.ts
  src/controllers/signAccountOp/helper.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
Labels: enhancement

#714 Bug/ Partial or old balance displayed on the dashboard
  src/controllers/main/main.ts
  src/libs/portfolio/helpers.ts
Labels: bug

#712 Bug/ Transfer sw warning displayed for addresses in the address book
  src/controllers/transfer/transfer.ts
Labels: bug

#717 Fix: make sign message work for custom networks
  src/controllers/signMessage/signMessage.ts
Labels: bug

#718 Bug/ Portfolio controller state prepare racing condition
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
Labels: bug

#720 Fix: nonce discrepancy
  src/controllers/main/main.ts
Labels: bug

#721 Fix / PendingUserRequests Duplicating Id With AccountOpEoaBanners Id
  src/libs/banners/banners.ts
Labels: bug

#719 Add / USDC.E mapping
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/helpers.ts
Labels: enhancement

#725 Fix: estimation failure on reject
  src/controllers/main/main.ts
Labels: bug

#716 Bug/reflect pending state
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/transfer/transfer.test.ts
  src/controllers/transfer/transfer.ts
  src/libs/deployless/deployless.ts
  src/libs/portfolio/helpers.ts
  src/libs/portfolio/portfolio.ts
  src/libs/portfolio/portfolioView.ts
  src/services/validations/validate.ts
Labels: enhancement

#726 Fix: even if pinned, do not filter it out because simulation suffers
  src/libs/portfolio/portfolio.ts
Labels: bug

#727 Humanizer: Update swap/wrap parser
  src/services/humanReadableTransactions/transactionSummary.ts
Labels: enhancement

#728 Fix: check if fee speeds are set before declaring error in sign account op
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#730 Fix: declare submitted op failure if not found
  src/controllers/activity/activity.ts
Labels: bug

#732 Fix: do not re-add accountOp on estimation
  src/controllers/main/main.ts
Labels: bug

#729 Humanizer: add id to HumanizerVisualization
  src/libs/humanizer/humanizeMessages.test.ts
  src/libs/humanizer/humanizerModules.test.ts
  src/libs/humanizer/index.test.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/interfaces.ts
  src/libs/humanizer/lazyStorage.ts
  src/libs/humanizer/modules/sushiSwapModule.ts
  src/libs/humanizer/typedMessageModules/fallbackModule.ts
  src/libs/humanizer/utils.ts
Labels: bug, enhancement

#738 Humanizer: parseActions: add checks for arg types
  src/services/humanReadableTransactions/transactionSummary.ts
Labels: bug
