Repository AmbireTech/ambire-common, pull requests merged in 2024-05, with the labels that each got.

#744 Add remove liquidity humanization parsing and bug fixes
  src/services/humanReadableTransactions/transactionSummary.ts
Labels: enhancement

#745 Bug/ Wrong error emitted in settings controller after `withStatus` changes in `EventEmitter`
  src/controllers/settings/settings.ts
Labels: bug

#746 Humanizer: Add custom network native token symbol update
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/humanizer/humanizerModules.test.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/parsers/humanizerMetaParsing.ts
Labels: bug, enhancement

#747 Transfer: Add checks for entered amount in transfer controller
  src/controllers/transfer/transfer.ts
  src/services/validations/validate.ts
Labels: bug

#752 Change the rpc for the mantle test
  src/controllers/settings/settings.test.ts
Labels: bug

#751 Feature / Invite Controller
  src/controllers/invite/invite.ts
  src/controllers/main/main.ts
Labels: enhancement

#755 Benzina: Fix: 'NATIVE' token symbol
  src/libs/humanizer/index.ts
  src/libs/humanizer/parsers/humanizerMetaParsing.ts
Labels: bug

#756 Fix: custom network deploy txn estimation
  src/libs/estimate/estimate.ts
  src/services/bundlers/bundler.ts
Labels: bug

#757 Bug humanizer storage
  src/libs/humanizer/index.ts
  src/libs/humanizer/lazyStorage.ts
Labels: bug, enhancement

#759 Humanizer: Add hidden wrapping token for wrap/unwrap
  src/libs/humanizer/humanizerFuncs.ts
  src/libs/humanizer/humanizerModules.test.ts
  src/libs/humanizer/modules/wrapped.ts
  src/libs/humanizer/utils.ts
Labels: enhancement

#760 Fix: verify message
  contracts/UniversalSigValidator.sol
  contracts/compiled/UniversalSigValidator.json
  src/libs/signMessage/signMessage.test.ts
  src/libs/signMessage/signMessage.ts
Labels: bug

#762 Bug/ Transfer amount exceeds balance error
  src/controllers/transfer/transfer.ts
  src/services/validations/validate.ts
Labels: bug

#763 Fix: v1 accounts signing
  src/consts/addresses.ts
  src/controllers/signMessage/signMessage.ts
  src/libs/signMessage/signMessage.test.ts
  src/libs/signMessage/signMessage.ts
Labels: bug

#761 Bug/ Infinite loading on selected account change in Transaction History/Signed Messages
  src/controllers/activity/activity.test.ts
  src/controllers/activity/activity.ts
  src/controllers/main/main.ts
Labels: bug

#768 Add pre-parsig for humanizer calls
  src/libs/humanizer/index.ts
  src/libs/humanizer/modules/preProcessModule.ts
Labels: bug

#767 Remove / Estimation from Main
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/banners/banners.ts
Labels: enhancement

#765 Enhancement/ Fix laggy transfer fields
  src/controllers/main/main.ts
  src/controllers/transfer/transfer.test.ts
  src/controllers/transfer/transfer.ts
  src/interfaces/transfer.ts
  src/services/validations/validate.ts
Labels: bug, enhancement

#769 Update NFT deployless return structure
  contracts/compiled/NFTGetter.json
  contracts/deployless/NFTGetter.sol
  dist/contracts/compiled/NFTGetter.json
  src/libs/deployless/deployless.ts
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/index.ts
  src/libs/portfolio/interfaces.ts
Labels: enhancement

#773 Fix: humanizer: async token info learning custom networks
  src/libs/humanizer/modules/tokens.ts
  src/libs/humanizer/utils.ts
Labels: enhancement

#776 Compile updated nft deployless and function
  dist/contracts/compiled/IERC20.json
  dist/src/consts/gasTankFeeTokens.js
  dist/src/consts/gasTankFeeTokens.js.map
  dist/src/consts/pinnedTokens.js
  dist/src/consts/pinnedTokens.js.map
  dist/src/libs/portfolio/customToken.js
  dist/src/libs/portfolio/customToken.js.map
  dist/src/libs/portfolio/getOnchainBalances.js
  dist/src/libs/portfolio/getOnchainBalances.js.map
  dist/src/libs/portfolio/helpers.js
  dist/src/libs/portfolio/helpers.js.map
  src/interfaces/userRequest.ts
  src/libs/accountOp/accountOp.ts
Labels: enhancement
