Repository AmbireTech/ambire-common, pull requests merged in 2024-07, with the labels that each got.

#838 Fix: Portfolio updates, when to do a SignAccountOp destroy, additional hints in simulation
  src/controllers/main/main.ts
  src/libs/portfolio/helpers.ts
Labels: bug

#839 Fix: SA estimateGas not deployed
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateGas.ts
Labels: bug

#837 Humanizer: bug fixes
  src/libs/humanizer/const/abis/Uniswap.ts
  src/libs/humanizer/humanizerModules.test.ts
  src/libs/humanizer/modules/Uniswap/uniUniversalRouter.ts
  src/libs/humanizer/modules/Uniswap/uniV2.ts
  src/libs/humanizer/modules/Uniswap/uniV3.ts
  src/libs/humanizer/modules/Uniswap/uniswap.test.ts
  src/libs/humanizer/modules/Uniswap/utils.ts
  src/libs/humanizer/modules/Wrapping/wrapping.test.ts
  src/libs/humanizer/modules/Wrapping/wrapping.ts
Labels: bug

#843 Fix / Wrong Banner (Pending dApp Requests) when Benzin is Opened
  src/libs/banners/banners.ts
Labels: bug

#844 Bug / Account Adder inconsistent (occasionally failing) test
  src/controllers/accountAdder/accountAdder.test.ts
Labels: bug

#845 Add errors on wrong signer requested by dapp for signing
  src/controllers/main/main.ts
Labels: bug

#846 Fix: return back from EstimationError
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#848 Update error message for wrong signer requested on signing
  src/controllers/main/main.ts
Labels: enhancement

#847 Fix: sign EP authorization only once
  src/controllers/main/main.ts
  src/libs/userOperation/userOperation.ts
Labels: bug

#793 Feature/ Remove account
  src/controllers/accounts/accounts.test.ts
  src/controllers/accounts/accounts.ts
  src/controllers/actions/actions.test.ts
  src/controllers/actions/actions.ts
  src/controllers/activity/activity.test.ts
  src/controllers/activity/activity.ts
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/signMessage/signMessage.test.ts
  src/controllers/signMessage/signMessage.ts
Labels: enhancement

#854 Bug/ Eslint not working with `node_modules` installed
  .eslintrc.js
  package-lock.json
  package.json
Labels: bug, configuration

#840 Feature/learn from trace call
  src/consts/networks.ts
  src/controllers/main/main.ts
  src/controllers/networks/networks.test.ts
  src/controllers/networks/networks.ts
  src/controllers/portfolio/portfolio.ts
  src/interfaces/network.ts
  src/libs/deployless/deployless.ts
  src/libs/deployless/simulateDeployCall.ts
  src/libs/main/main.ts
  src/libs/networks/networks.test.ts
  src/libs/networks/networks.ts
  src/libs/tracer/debugTraceCall.ts
  src/services/bundlers/bundler.test.ts
Labels: enhancement

#831 Feature: RBF
  src/controllers/activity/activity.test.ts
  src/controllers/activity/activity.ts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/helper.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/accountState/accountState.test.ts
  src/libs/accountState/accountState.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/portfolio/getOnchainBalances.ts
  test/helpers.ts
Labels: enhancement

#857 Fix: function typo
  src/controllers/main/main.ts
Labels: bug

#859 Bug/ Removing an account removes the keys of all other accounts
  src/controllers/keystore/keystore.test.ts
  src/controllers/keystore/keystore.ts
  src/controllers/main/main.ts
Labels: bug

#860 Fix / Select Default Account
  src/controllers/accounts/accounts.ts
Labels: bug

#863 Remove fallback typed message humanizer module as it appears buggy
  src/libs/humanizer/humanizeMessages.test.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/typedMessageModules/fallbackModule.ts
  src/libs/humanizer/typedMessageModules/index.ts
Labels: enhancement

#833 Feature/wrap native gas tank
  contracts/compiled/WETH.json
  src/consts/networks.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/interfaces/network.ts
  src/interfaces/userRequest.ts
  src/libs/actions/actions.ts
  src/libs/main/main.ts
  src/libs/transfer/userRequest.ts
Labels: enhancement

#858 Fix: re-estimate on nonce discrepancy
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/main/main.ts
  src/libs/tracer/debugTraceCall.ts
Labels: bug

#864 Fix: estimation nonce
  src/controllers/main/main.ts
  src/libs/estimate/estimate.ts
Labels: bug

#824 Fix: none state-override rpcs
  src/controllers/main/main.ts
  src/libs/main/main.ts
  src/libs/portfolio/getOnchainBalances.ts
Labels: bug

#849 Fix: verifying messages with state override only when supported
  src/controllers/signMessage/signMessage.ts
  src/libs/signMessage/signMessage.test.ts
  src/libs/signMessage/signMessage.ts
Labels: bug

#855 Enhancement/ Improve portfolio related UX when an RPC is down
  src/controllers/portfolio/portfolio.ts
  src/libs/banners/banners.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolioView.ts
Labels: enhancement

#865 Shorten error
  src/libs/estimate/errors.ts
Labels: bug

#868 Do not show nonce discrepancy error
  src/controllers/main/main.ts
Labels: enhancement

#870 Add humanizer type 'message' for hex messages
  src/libs/humanizer/humanizerFuncs.ts
  src/libs/humanizer/index.test.ts
  src/libs/humanizer/interfaces.ts
  src/libs/humanizer/testHelpers.ts
  src/libs/humanizer/utils.ts
Labels: enhancement

#862 Change/ Reject all requests except sign-account-op on window close
  src/controllers/actions/actions.test.ts
  src/controllers/actions/actions.ts
  src/controllers/main/main.ts
Labels: enhancement

#866 Bug/ Forever pending dapp request if account state is missing
  src/controllers/main/main.ts
Labels: bug

#869 Bug/ All providers marked as !isWorking on `updateAccountState` call
  src/controllers/accounts/accounts.ts
  src/controllers/main/main.ts
Labels: bug

#878 Fix / Connect Dapp on an Uninitialized Extension
  src/controllers/main/main.ts
Labels: bug

#875 Fix: taking gas price
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#881 Fix: react to incorrect user op nonce
  src/controllers/main/main.ts
  src/libs/estimate/errors.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/interfaces.ts
Labels: bug

#876 Only one pending network
  src/controllers/main/main.ts
Labels: enhancement

#883 fix: remove onSignSuccess passing networks
  src/controllers/main/main.ts
Labels: bug

#882 Humanizer: Delete some internal reliance on humanizerMeta
  src/libs/humanizer/humanizeMessages.test.ts
  src/libs/humanizer/humanizerFuncs.ts
  src/libs/humanizer/humanizerModules.test.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/interfaces.ts
  src/libs/humanizer/modules/FallbackHumanizer/fallbackHumanizer.test.ts
  src/libs/humanizer/modules/Sushiswap/sushiswap.test.ts
  src/libs/humanizer/modules/Tokens/tokens.test.ts
  src/libs/humanizer/modules/Tokens/tokens.ts
  src/libs/humanizer/modules/Uniswap/index.ts
  src/libs/humanizer/modules/WALLET/wallet.test.ts
  src/libs/humanizer/modules/Wrapping/wrapping.test.ts
  src/libs/humanizer/modules/Wrapping/wrapping.ts
  src/libs/humanizer/parsers/index.ts
  src/libs/humanizer/testHelpers.ts
  src/libs/humanizer/typedMessageModules/erc721Module.ts
  src/libs/humanizer/utils.ts
Labels: enhancement

#874 Add: basic nft simulation diffs
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/interfaces.ts
Labels: enhancement

#892 Revert "Merge pull request #874 from AmbireTech/add/nft-simulation-di…
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/interfaces.ts
Labels: bug

#895 Humanizer: disable splitting and squashing calls
  src/libs/humanizer/modules/Uniswap/index.ts
  src/libs/humanizer/modules/Uniswap/interfaces.ts
  src/libs/humanizer/modules/Uniswap/uniUniversalRouter.ts
  src/libs/humanizer/modules/Uniswap/uniV2.ts
  src/libs/humanizer/modules/Uniswap/uniV3.ts
  src/libs/humanizer/modules/Uniswap/uniswap.test.ts
  src/libs/humanizer/modules/Uniswap/utils.ts
  src/libs/humanizer/modules/Wrapping/wrapping.test.ts
  src/libs/humanizer/modules/Wrapping/wrapping.ts
Labels: bug, enhancement

#867 Fix/4337 gas price updates
  src/controllers/main/main.ts
  src/controllers/networks/networks.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/estimate/errors.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/interfaces.ts
  src/libs/networks/networks.ts
  src/services/bundlers/bundler.ts
Labels: bug

#888 Fix: estimate gas fallback
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateGas.ts
Labels: bug

#894 Bug/ `rpc-down` banners duplicate id
  src/libs/banners/banners.ts
  src/libs/portfolio/portfolioView.ts
Labels: bug

#898 Config/ Add missing files and folders to .eslintignore
  .eslintignore
Labels: configuration

#902 Fix: add WETH as a fee token on optimism, arbitrum
  src/consts/gasTankFeeTokens.ts
Labels: bug

#836 Update/portfolio block number for portfolio view
  contracts/compiled/BalanceGetter.json
  contracts/deployless/BalanceGetter.sol
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.ts
  src/libs/portfolio/portfolioView.ts
Labels: enhancement

#896 Fix / Pending Actions Order
  src/controllers/actions/actions.test.ts
  src/controllers/main/main.ts
  src/interfaces/userRequest.ts
Labels: bug, enhancement, refactoring

#910 Fix failing portolio tests
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/portfolio.test.ts
  src/libs/portfolio/portfolio.ts
Labels: bug, enhancement

#911 Bug/ Simulation gone on portfolio reload (Basic Account)
  src/controllers/main/main.ts
Labels: bug

#899 Add paraswap humanizer
  package.json
  src/hooks/useConstants/types.ts
  src/services/humanizers/Paraswap.ts
  src/services/humanizers/index.ts
Labels: enhancement

#893 Add basic nft simulation diffs
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.test.ts
Labels: enhancement
