Repository AmbireTech/ambire-common, pull requests merged in 2024-08, with the labels that each got.

#909 Enhancement/ USD field in transfer
  src/controllers/transfer/transfer.ts
  src/interfaces/transfer.ts
  src/libs/transfer/amount.ts
  src/services/validations/validate.ts
Labels: enhancement

#917 Add post processing for additional token hint
  src/libs/humanizer/index.test.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/modules/PostProcessing/index.ts
  src/libs/humanizer/modules/PostProcessing/postProcessModule.ts
  src/libs/humanizer/modules/PostProcessing/postProcessing.test.ts
  src/libs/humanizer/modules/Wrapping/wrapping.test.ts
  src/libs/humanizer/modules/Wrapping/wrapping.ts
  src/libs/humanizer/utils.ts
Labels: enhancement

#906 Feature / Import Default Seed Phrase
  src/controllers/accountAdder/accountAdder.ts
  src/controllers/accounts/accounts.ts
  src/controllers/keystore/keystore.test.ts
  src/controllers/keystore/keystore.ts
  src/controllers/main/main.ts
  src/interfaces/account.ts
  src/libs/keys/keys.ts
Labels: enhancement

#904 Add assetInfo service
  src/libs/portfolio/index.ts
  src/libs/portfolio/portfolio.ts
  src/services/assetInfo/assetInfo.test.ts
  src/services/assetInfo/assetInfo.ts
  src/services/assetInfo/index.ts
Labels: enhancement

#924 Add destination chain id for bridging tokens
  src/libs/humanizer/interfaces.ts
  src/libs/humanizer/modules/Across/across.test.ts
  src/libs/humanizer/modules/Across/index.ts
  src/libs/humanizer/modules/Socket/socket.test.ts
  src/libs/humanizer/modules/Socket/socketModules.ts
  src/libs/humanizer/utils.ts
Labels: enhancement

#926 Bug/ Wrong condition in domains controller
  src/controllers/domains/domains.ts
Labels: bug

#925 Add/ Extension invite code in wallet rewards data
  src/hooks/useRewards/types.ts
  src/hooks/useRewards/useRewards.ts
Labels: enhancement

#920 Feature / Add to Queue Button
  src/controllers/actions/actions.ts
  src/controllers/main/main.ts
  src/controllers/transfer/transfer.test.ts
  src/controllers/transfer/transfer.ts
  src/interfaces/banner.ts
  src/libs/banners/banners.ts
Labels: enhancement

#931 Bug/ Transfer selected token not updated after updating the acc
  src/controllers/transfer/transfer.ts
Labels: bug

#908 Add feeCall to estimateGas (SA)
  src/libs/calls/calls.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/estimateGas.ts
  src/libs/estimate/estimateHelpers.ts
Labels: bug

#936 Bug / Ledger re-connect logic fails to click because of a bad ref
  src/controllers/main/main.ts
Labels: bug

#934 Fix / Entry Point Authorization Action Issues
  src/controllers/actions/actions.ts
  src/controllers/main/main.ts
Labels: bug

#939 Feature: better maxPriorityFeePerGas estimation
  src/consts/networks.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/interfaces/network.ts
  src/libs/gasPrice/gasPrice.ts
  src/libs/gasPrice/tests/1559Network.test.ts
Labels: bug, enhancement

#937 Enhancement/ Don't ask for entry point authorization if already signed
  src/controllers/main/main.ts
  src/libs/main/main.ts
Labels: enhancement

#938 Enhancement/ Calculate dollar value saved by gas tank in `signAccountOp`
  src/consts/signAccountOp.ts
  src/controllers/signAccountOp/signAccountOp.ts
Labels: enhancement

#941 Fix: RBF in history on ethereum
  src/controllers/activity/activity.ts
Labels: bug

#940 Disable gas usage of xWallet if not on gasTank network
  src/consts/gasTankFeeTokens.ts
  src/libs/portfolio/helpers.ts
Labels: bug

#943 Add entry point authorization humanization
  src/libs/humanizer/humanizeMessages.test.ts
  src/libs/humanizer/humanizerFuncs.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/interfaces.ts
  src/libs/humanizer/typedMessageModules/entryPointModule.ts
  src/libs/humanizer/typedMessageModules/erc20Module.ts
  src/libs/humanizer/typedMessageModules/erc721Module.ts
  src/libs/humanizer/typedMessageModules/permit2Module.ts
Labels: bug, enhancement

#950 Feature: more aggressive tips
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/gasPrice/gasPrice.ts
  src/libs/gasPrice/tests/1559Network.test.ts
Labels: enhancement

#948 Fix/ Improve errors state, fix `readyToSign` and more in `signAccountOp`
  src/controllers/main/main.ts
  src/controllers/signAccountOp/helper.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/account/account.ts
Labels: bug

#952 Feature / Add Claim Vesting Rewards Request
  src/libs/portfolio/index.ts
  src/libs/portfolio/interfaces.ts
  src/libs/transfer/userRequest.ts
Labels: enhancement

#953 Remove / Benzin Action when a new Action Arrives
  src/controllers/actions/actions.ts
Labels: enhancement

#954 Change: base fee calculations
  src/consts/networks.ts
  src/controllers/networks/networks.ts
  src/interfaces/network.ts
  src/libs/gasPrice/gasPrice.ts
Labels: bug, enhancement

#951 Bug/ Mismatch between `availableAmount` and `token.amount` in `feePaymentOptions`
  src/libs/estimate/estimate.ts
Labels: bug

#955 Fix/status updates sign acc op
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#933 Add networkId to gasFeePayment in accountOp
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/accountOp/accountOp.ts
  src/services/assetInfo/assetInfo.test.ts
  src/services/assetInfo/assetInfo.ts
Labels: bug

#957 Remove plaintext message humanizer
  src/libs/humanizer/humanizerFuncs.ts
  src/libs/humanizer/index.test.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/utils.ts
Labels: enhancement

#962 Fix: relayer networks nonce discrepancy
  src/controllers/activity/activity.ts
  src/controllers/main/main.ts
  src/libs/estimate/estimate.ts
Labels: bug

#961 Bug/ Swap expired error not handled for basic accounts
  src/libs/estimate/errors.ts
Labels: bug

#956 Fix / Potential Issue With Duplicate Accounts
  src/controllers/accounts/accounts.ts
  src/libs/account/account.ts
Labels: bug

#947 Add uniReducer
  src/libs/humanizer/modules/Uniswap/uniUniversalRouter.ts
  src/libs/humanizer/modules/Uniswap/uniV3.ts
  src/libs/humanizer/modules/Uniswap/uniswap.test.ts
  src/libs/humanizer/modules/Uniswap/utils.ts
  src/libs/humanizer/modules/Wrapping/wrapping.test.ts
Labels: enhancement

#913 Add debug tracecall for nfts
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.ts
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/helpers.test.ts
  src/libs/portfolio/helpers.ts
  src/libs/portfolio/interfaces.ts
  src/libs/tracer/debugTraceCall.test.ts
  src/libs/tracer/debugTraceCall.ts
Labels: enhancement

#964 Fix / Dashboard Simulation Cleanup After Deleting the Last Call from an AccountOp
  src/controllers/main/main.ts
Labels: bug

#968 Handle EIP-2612 with SA
  src/controllers/main/main.ts
  src/controllers/signMessage/signMessage.ts
Labels: enhancement

#973 Bug/ Missing emit update in `#emitSigningErrorAndResetToReadyToSign`
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#974 Humanizer/ update gas tank module
  src/libs/humanizer/modules/GasTankModule/gasTank.test.ts
  src/libs/humanizer/modules/GasTankModule/gasTankModule.ts
Labels: enhancement

#960 Enhancement/ Sign account op warnings
  src/consts/signAccountOp/errorHandling.ts
  src/consts/signAccountOp/gas.ts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/helper.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/interfaces/signAccountOp.ts
  src/libs/portfolio/helpers.ts
  src/libs/portfolio/interfaces.ts
Labels: enhancement

#970 Refactoring / Keys Label (Part of the SettingsController refactoring)
  src/controllers/accountAdder/accountAdder.test.ts
  src/controllers/accountAdder/accountAdder.ts
  src/controllers/emailVault/emailVault.test.ts
  src/controllers/keystore/keystore.test.ts
  src/controllers/keystore/keystore.ts
  src/controllers/main/main.ts
  src/controllers/settings/settings.test.ts
  src/controllers/settings/settings.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/interfaces/keyIterator.ts
  src/interfaces/keystore.ts
  src/interfaces/settings.ts
  src/libs/account/account.test.ts
  src/libs/humanizer/index.test.ts
  src/libs/keyIterator/keyIterator.ts
  src/libs/keys/keys.ts
  src/libs/keystoreSigner/keystoreSigner.test.ts
  src/libs/signMessage/signMessage.test.ts
  test/helpers.ts
Labels: refactoring

#976 fix email vault tests
  src/libs/emailVault/emailVault.test.ts
  src/libs/polling/polling.test.ts
Labels: bug

#921 Feature/erc 5792
  src/controllers/main/main.ts
  src/libs/actions/actions.ts
  src/libs/estimate/errors.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/main/main.ts
  src/services/sponsorship/paymasterSponsor.ts
Labels: enhancement

#972 Enable top up
  src/consts/gasTankFeeTokens.ts
  src/libs/portfolio/helpers.ts
Labels: enhancement

#967 Fix: identified by tx
  src/consts/networks.ts
  src/controllers/activity/activity.test.ts
  src/controllers/activity/activity.ts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/helper.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/interfaces/network.ts
  src/libs/accountOp/submittedAccountOp.ts
  src/libs/userOperation/userOperation.ts
  src/services/explorers/jiffyscan.ts
Labels: bug, refactoring
