Repository AmbireTech/ambire-common, pull requests merged in 2024-12, with the labels that each got.

#1142 Fix / Swap & Bridge Auto Reset of the toSelectedToken
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug

#1141 Humanizer: swap and bridge humanization fix + add steth action
  src/libs/humanizer/const/abis/Lido.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/modules/Lido/index.ts
  src/libs/humanizer/modules/Lido/lido.test.ts
  src/libs/humanizer/modules/Socket/socketModules.ts
Labels: bug

#1143 ERC-5792: feedback to the dapp
  src/controllers/main/main.ts
  src/interfaces/userRequest.ts
  src/libs/accountOp/submittedAccountOp.ts
  src/services/explorers/jiffyscan.ts
Labels: bug

#1147 Fix: activity.ts findMessage
  src/controllers/activity/activity.ts
Labels: bug

#1061 Update legends nft contract
  contracts/LegendsNft.sol
  contracts/LegendsNftImplementation.sol
  contracts/compiled/LegendsNft.json
  contracts/deployless/LegendsNftUpgradableProxy.sol
  hardhat.config.ts
  scripts/deployLegendsNft.js
  test/LegendsNft/LegendsNft.ts
  tsconfig.json
Labels: enhancement

#1150 Add: pollTxnId fail limit
  src/libs/accountOp/submittedAccountOp.ts
Labels: bug

#1151 Handle / Failed to Get txnId
  src/controllers/main/main.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/interfaces/banner.ts
  src/interfaces/swapAndBridge.ts
  src/libs/banners/banners.ts
Labels: enhancement

#1153 Disable estimateGas for all except Arbitrum
  src/consts/networks.ts
Labels: bug

#1152 Forbid gas tank usage on an empty account
  src/controllers/signAccountOp/signAccountOp.ts
Labels: enhancement

#1114 Enhancement / Error Logging
  src/controllers/eventEmitter/eventEmitter.ts
Labels: enhancement

#1138 ERC-7677 gas sponsorship
  src/consts/networks.ts
  src/controllers/main/main.ts
  src/controllers/networks/networks.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/interfaces/network.ts
  src/interfaces/userRequest.ts
  src/libs/accountOp/accountOp.ts
  src/libs/erc7677/erc7677.ts
  src/libs/erc7677/types.ts
  src/libs/errorDecoder/customErrors.ts
  src/libs/errorDecoder/handlers/paymaster.ts
  src/libs/errorHumanizer/errors.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimateBundler.test.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/interfaces.ts
  src/libs/main/main.ts
  src/libs/networks/networks.ts
  src/libs/paymaster/paymaster.ts
  src/libs/userOperation/userOperation.ts
  src/services/bundlers/bundler.test.ts
  src/services/bundlers/bundler.ts
  src/services/paymaster/FailedSponsorships.ts
  src/services/paymaster/PaymasterFactory.ts
  src/services/paymaster/index.ts
  src/services/sponsorship/paymasterSponsor.ts
Labels: enhancement

#1158 Update: character names in humanizer
  src/libs/humanizer/modules/Legends/index.ts
  src/libs/humanizer/modules/Legends/legends.test.ts
Labels: enhancement

#1161 Humanizer: Fix staking humanizer
  src/consts/addresses.ts
  src/libs/humanizer/modules/WALLET/index.ts
  src/libs/humanizer/modules/WALLET/stakingPools.ts
Labels: bug, enhancement

#1163 Fix / Basic Account Estimation Error Due to a Pending Approval
  src/controllers/activity/activity.ts
  src/controllers/main/main.ts
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/interfaces/banner.ts
  src/interfaces/swapAndBridge.ts
  src/libs/banners/banners.ts
  src/libs/swapAndBridge/swapAndBridge.ts
Labels: bug

#1145 Fix / Exclude routes with protocol fees for which the user does not have sufficient funds to pay
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/interfaces/swapAndBridge.ts
  src/services/socket/api.ts
  src/utils/formatDecimals/formatDecimals.test.ts
  src/utils/formatDecimals/formatDecimals.ts
Labels: bug

#1162 Feature/custom networks paymaster
  src/consts/gasTankFeeTokens.ts
  src/consts/networks.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/controllers/networks/networks.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/errorDecoder/customErrors.ts
  src/libs/errorHumanizer/broadcastErrorHumanizer.ts
  src/libs/errorHumanizer/errors.ts
  src/libs/errorHumanizer/humanizeCommonCases.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.test.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/networks/networks.ts
  src/libs/paymaster/paymaster.ts
  src/libs/userOperation/userOperation.ts
  src/services/bundlers/bundler.test.ts
  src/services/bundlers/bundler.ts
  src/services/paymaster/FailedPaymasters.ts
  src/services/paymaster/FailedSponsorships.ts
  src/services/paymaster/PaymasterFactory.ts
Labels: enhancement

#1167 Allow relayer broadcast for BNB and other relayer networks
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/estimate/estimate.ts
  src/libs/networks/networks.ts
  src/libs/signMessage/signMessage.ts
Labels: bug

#1168 Fix / SignAccountOp Updates While Signing or Broadcasting
  src/controllers/main/main.ts
Labels: bug

#1173 Update/ Improve rpc error handler decoding success
  src/libs/errorDecoder/errorDecoder.test.ts
  src/libs/errorDecoder/handlers/rpc.ts
  src/libs/errorDecoder/helpers.ts
Labels: enhancement

#1176 Fix/fe state on u op activator call
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/estimate/estimateViaEntryPoint.ts
  src/libs/userOperation/userOperation.ts
Labels: bug

#1177 Dapp Catalog: add legends to dapp catalog
  src/consts/dappCatalog.json
  src/controllers/dapps/dapps.ts
Labels: enhancement

#1169 Improve/estimation slow request
  src/controllers/accounts/accounts.ts
  src/controllers/eventEmitter/eventEmitter.ts
  src/controllers/main/main.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/estimateEOA.ts
  src/libs/estimate/estimateWithRetries.ts
  src/libs/gasPrice/gasPrice.ts
  src/services/bundlers/bundler.ts
  src/services/errorEmitter/emitter.ts
Labels: enhancement

#1182 A better error message for preVerificationGas not enough
  src/controllers/main/main.ts
Labels: bug

#1181 Fix / Active Route Removal
  src/controllers/main/main.ts
  src/libs/swapAndBridge/swapAndBridge.ts
Labels: bug

#1171 Fix/ Update networksWithAccountStateError on `main.removeNetwork` (accountAdder)
  src/controllers/accountAdder/accountAdder.ts
  src/controllers/main/main.ts
Labels: bug

#1149 Update/ Portfolio hints banner improve ux and clean up hints logic
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/libs/banners/banners.ts
  src/libs/portfolio/helpers.test.ts
  src/libs/portfolio/helpers.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.test.ts
  src/libs/portfolio/portfolio.ts
  src/services/assetInfo/assetInfo.ts
Labels: enhancement

#1180 Refactor/emit error as callback
  src/controllers/eventEmitter/eventEmitter.ts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.test.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/estimateEOA.ts
  src/libs/estimate/estimateWithRetries.ts
  src/services/bundlers/bundler.ts
  src/services/errorEmitter/emitter.ts
Labels: enhancement

#1185 Enhancement/ Nft already minted human readable error
  src/libs/errorDecoder/handlers/revert.ts
  src/libs/errorHumanizer/errors.ts
Labels: enhancement

#1179 Simulation: prioritize enumerable data
  contracts/compiled/NFTGetter.json
  contracts/deployless/NFTGetter.sol
  src/services/assetInfo/assetInfo.ts
Labels: enhancement

#1187 Fix / Unable to open the popup window due to opened action window
  src/controllers/actions/actions.ts
  src/controllers/main/main.ts
Labels: bug

#1188 Enhancement/ Improve error humanization
  src/controllers/main/main.test.ts
  src/libs/errorDecoder/errorDecoder.test.ts
  src/libs/errorDecoder/errorDecoder.ts
  src/libs/errorDecoder/handlers/custom.ts
  src/libs/errorDecoder/handlers/index.ts
  src/libs/errorDecoder/helpers.ts
  src/libs/errorDecoder/types.ts
  src/libs/errorHumanizer/errors.ts
  src/libs/errorHumanizer/estimationErrorHumanizer.test.ts
  src/libs/errorHumanizer/estimationErrorHumanizer.ts
  src/libs/errorHumanizer/helpers.test.ts
  src/libs/errorHumanizer/helpers.ts
  src/libs/errorHumanizer/humanizeCommonCases.test.ts
  src/libs/estimate/estimate.test.ts
Labels: enhancement

#1087 Simulation: debug_traceCall: make mint and burn simulation possible
  contracts/compiled/NFTGetter.json
  contracts/deployless/NFTGetter.sol
  src/consts/deployless.ts
  src/libs/estimate/estimateEOA.ts
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/portfolio.test.ts
  src/libs/tracer/debugTraceCall.test.ts
  src/libs/tracer/debugTraceCall.ts
  src/utils/simulationStateOverride.ts
Labels: bug
