Repository AmbireTech/ambire-common, pull requests merged in 2024-03, with the labels that each got.

#635 Feature: Paymaster for native & Optimism fee optimisation
  contracts/compiled/Estimation.json
  contracts/deployless/Estimation.sol
  src/consts/networks.ts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/interfaces/networkDescriptor.ts
  src/libs/estimate/estimate.ts
  src/libs/gasPrice/gasPrice.ts
  src/libs/userOperation/userOperation.ts
Labels: enhancement

#629 Humanizer uniswap fix, simulation addresses, storage r/w optimization
  src/libs/humanizer/humanizerFuncs.test.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/interfaces.ts
  src/libs/humanizer/modules/Uniswap/Commands.ts
  src/libs/humanizer/modules/Uniswap/index.ts
  src/libs/humanizer/modules/Uniswap/uniUnivarsalRouter.ts
  src/libs/humanizer/modules/fallBackHumanizer.ts
  src/libs/humanizer/parsers/humanizerMetaParsing.ts
  src/libs/humanizer/typedMessageModules/erc20Module.ts
  src/libs/humanizer/utils.ts
Labels: bug, enhancement

#643 Enhancement/ Better unknown recipient ux
  src/controllers/transfer/transfer.ts
  src/interfaces/transfer.ts
Labels: enhancement

#647 Fix: erc 4337 estimation on optimism
  src/consts/networks.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/interfaces/networkDescriptor.ts
  src/libs/accountOp/accountOp.ts
  src/libs/gasPrice/gasPrice.ts
  src/services/bundlers/bundler.ts
Labels: bug

#650 Fix errors for EV shouldStopConfirmationPolling checks
  src/controllers/emailVault/emailVault.ts
Labels: bug

#655 Bug/ View only accounts aren't filtered from `feePaymentOptions`
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/utils/accounts.ts
Labels: bug

#649 Enhancement/ Manage account keys from the UI
  src/controllers/settings/settings.ts
  src/controllers/signAccountOp/signAccountOp.ts
Labels: enhancement

#660 Bug/ Transfer recipient address same address check is case sensitive
  src/services/validations/validate.ts
Labels: bug

#658 Parse non hex string to hex 'personal_sign'
  src/controllers/signMessage/signMessage.ts
Labels: bug

#659 Bug / Re-importing account with another key should update the associated keys of this account
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
Labels: bug

#661 Enhancement/ Merge network error banners into a single banner
  src/libs/banners/banners.ts
Labels: enhancement

#656 Enhancement/ ENS/UD reverse lookup
  package-lock.json
  package.json
  src/controllers/domains/domains.test.ts
  src/controllers/domains/domains.ts
  src/controllers/main/main.ts
  src/services/ensDomains/ensDomains.ts
  src/services/unstoppableDomains/unstoppableDomains.ts
Labels: enhancement

#665 Bug / Missing `expect` import in domains.test.ts
  src/controllers/domains/domains.test.ts
Labels: bug

#664 Bug / Account Adder - impors import fallback (+ add missing tests)
  src/libs/account/account.test.ts
  src/libs/account/account.ts
Labels: bug

#644 Feature: custom network
  .env-sample
  .github/workflows/tests.yml
  contracts/compiled/Estimation.json
  contracts/deployless/Estimation.sol
  src/consts/coingecko.ts
  src/consts/deploy.ts
  src/consts/feeTokens.ts
  src/consts/networks.ts
  src/controllers/activity/activity.test.ts
  src/controllers/activity/activity.ts
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/settings/settings.test.ts
  src/controllers/settings/settings.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/controllers/transfer/transfer.test.ts
  src/controllers/transfer/transfer.ts
  src/interfaces/networkDescriptor.ts
  src/interfaces/settings.ts
  src/libs/account/account.ts
  src/libs/accountOp/accountOp.test.ts
  src/libs/accountOp/accountOp.ts
  src/libs/deploy/singleton.ts
  src/libs/deployless/deployless.test.ts
  src/libs/deployless/deployless.ts
  src/libs/deployless/simulateDeployCall.ts
  src/libs/estimate/customNetworks.ts
  src/libs/estimate/errors.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/interfaces.ts
  src/libs/gasPrice/gasPrice.ts
  src/libs/humanizer/utils.ts
  src/libs/portfolio/gecko.ts
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/helpers.ts
  src/libs/portfolio/icons.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.test.ts
  src/libs/portfolio/portfolio.ts
  src/libs/settings/settings.ts
  src/libs/signMessage/signMessage.ts
  src/libs/singleton/singleton.ts
  src/libs/userOperation/userOperation.ts
  src/services/bundlers/bundler.test.ts
  src/services/bundlers/bundler.ts
  src/services/validations/validate.ts
Labels: enhancement

#667 Change/ `reverseLookupEns` to follow ENS's guidelines
  src/controllers/domains/domains.ts
  src/services/ensDomains/ensDomains.ts
Labels: bug

#668 Bug / Merge the (probably up-to-date) account `associatedKeys` from the Account Adder (account on page) with the ones existing when determine its import status
  src/libs/account/account.test.ts
  src/libs/account/account.ts
Labels: bug

#670 Bug / Detect differences for account stored associated keys, the keys coming from the account found on page and cover different scenarios with having associatedKeys and imported keys alongside
  src/libs/account/account.test.ts
  src/libs/account/account.ts
Labels: bug

#673 Feature: ERC-4337 bundler estimation
  contracts/compiled/AmbireAccountNoRevert.json
  src/consts/deploy.ts
  src/consts/networks.ts
  src/controllers/activity/activity.ts
  src/controllers/main/main.ts
  src/controllers/settings/settings.test.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/interfaces/networkDescriptor.ts
  src/libs/accountOp/accountOp.ts
  src/libs/calls/calls.ts
  src/libs/estimate/errors.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateArbitrum.ts
  src/libs/estimate/estimateBundler.test.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/estimateViaEntryPoint.ts
  src/libs/estimate/interfaces.ts
  src/libs/estimate/refund.ts
  src/libs/gasPrice/gasPrice.ts
  src/libs/portfolio/portfolio.ts
  src/libs/userOperation/userOperation.ts
  src/services/bundlers/bundler.test.ts
  src/services/bundlers/bundler.ts
  src/services/explorers/jiffyscan.ts
  src/services/provider/statisProvider.ts
  test/config.ts
  test/helpers.ts
Labels: enhancement

#674 Stop Arb debug_traceCall but show full support for txn simulation on Arb
  src/consts/networks.ts
  src/controllers/settings/settings.test.ts
  src/controllers/settings/settings.ts
  src/interfaces/networkDescriptor.ts
  src/libs/settings/settings.ts
Labels: enhancement

#663 Feature/ Address Book
  src/controllers/addressBook/addressBook.test.ts
  src/controllers/addressBook/addressBook.ts
  src/controllers/main/main.ts
Labels: enhancement

#676 Fix: bundler call gas limit
  src/libs/estimate/estimateBundler.ts
  src/services/bundlers/bundler.ts
Labels: bug

#677 Fix: state overrides so the bundler estimates correctly
  src/libs/estimate/estimateBundler.ts
  src/services/bundlers/bundler.ts
Labels: bug

#675 Feature/custom networks improvements
  src/consts/networks.ts
  src/controllers/main/main.ts
  src/controllers/settings/settings.ts
  src/interfaces/networkDescriptor.ts
  src/interfaces/settings.ts
  src/libs/settings/settings.test.ts
  src/libs/settings/settings.ts
Labels: enhancement
