Repository AmbireTech/ambire-common, pull requests merged in 2024-02, with the labels that each got.

#559 Feature: should not happen estimation errors handling
  src/controllers/main/main.ts
  src/libs/estimate/estimate.ts
Labels: enhancement

#558 Change/ Scope pinned tokens to a network
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.ts
Labels: enhancement

#562 Bug / Banner IDs should be unique, but not based on timestamps (because same error gets duplicated)
  src/libs/banners/banners.ts
Labels: bug

#563 Fix: sign account op freeze if bundler broadcast fails
  src/controllers/main/main.ts
Labels: bug

#560 Suggestion: last block refetch on gas price
  src/controllers/main/main.ts
  src/libs/gasPrice/gasPrice.ts
Labels: enhancement

#566 Fix: stop state updates on sign account op once signing begins
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug, enhancement

#565 Feature/ Reusable ENS and UD resolution
  src/controllers/transfer/transfer.test.ts
  src/controllers/transfer/transfer.ts
  src/interfaces/domains.ts
  src/interfaces/transfer.ts
  src/services/ensDomains/ensDomains.ts
  src/services/unstoppableDomains/unstoppableDomains.ts
  src/services/validations/validate.ts
Labels: enhancement

#568 Sign account op local user op
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateArbitrum.ts
Labels: enhancement

#571 Feature / Email Vault - new state for tracking secret upload
  src/controllers/emailVault/emailVault.ts
Labels: enhancement

#573 Fix portfolio.ts eslint errors
  src/libs/portfolio/portfolio.ts
Labels: enhancement

#579 Fix/handle estimation deployless errors
  src/libs/deployless/deployless.test.ts
  src/libs/deployless/deployless.ts
  src/libs/estimate/errors.ts
  src/libs/estimate/estimate.ts
Labels: bug

#584 Fix: hide tokens from portfolio without balance (and not preset)
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.ts
Labels: bug

#583 Fix: EOA simulation
  src/libs/deployless/deployless.ts
  src/libs/estimate/estimate.ts
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/portfolio.test.ts
Labels: bug

#585 Fix: Account related pinned tokens
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.ts
Labels: bug

#587 Bug/ Rewards and vesting flags are mixed up
  src/libs/portfolio/helpers.ts
Labels: bug

#589 Enhancement/ Handle portfolio malfunctions
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/banners/banners.ts
  src/libs/portfolio/portfolio.ts
Labels: enhancement

#567 Update email vault controller functionality
  src/controllers/emailVault/emailVault.test.ts
  src/controllers/emailVault/emailVault.ts
  src/controllers/main/main.test.ts
  src/libs/magicLink/magicLink.ts
  src/libs/polling/polling.test.ts
  src/libs/polling/polling.ts
Labels: bug, enhancement

#593 Delete/ `CachedResolvedDomain` typescript type
  src/interfaces/domains.ts
Labels: bug

#594 Bug/ Fee speeds error is displayed for a split second if fee speeds take longer do show
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#595 Bug/ Pinned gas tank tokens have a price of 0
  src/controllers/portfolio/portfolio.ts
Labels: bug

#596 Bug/ SignAccountOp can't estimate when the user doesn't have the native token in his portfolio
  src/controllers/main/main.ts
Labels: bug

#599 Fix/display relayer error
  src/consts/feeTokens.ts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/relayerCall/relayerCall.ts
Labels: bug

#604 Fix: remove fee call when sign begins
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#605 Fix: remove view only acc as payment options for other accounts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
Labels: bug

#606 Add: USDC as a fee token to the arb network
  src/consts/feeTokens.ts
Labels: bug

#607 Fix: silent errors in portfolio tests because of missing providers
  src/controllers/portfolio/portfolio.test.ts
Labels: bug

#608 Enable 4337/optimism
  src/consts/networks.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/estimate/estimate.ts
  src/libs/gasPrice/gasPrice.ts
Labels: bug, configuration

#603 Enhancement/ Refactor portfolio pinned logic
  src/consts/pinnedTokens.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/libs/portfolio/getNetworksWithAssets.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.ts
Labels: enhancement

#611 Bug/ Zero-balance tokens are preselected, amount/maxAmount comparsion doesn't work properly, can select a token with amount 0 `Transfer ctrl`
  src/controllers/transfer/transfer.ts
  src/services/validations/validate.ts
Labels: bug

#614 Fix: estimate the activator call as well
  src/libs/userOperation/userOperation.ts
Labels: bug

#616 Fix: user op estimation
  src/libs/estimate/estimate.ts
  src/libs/userOperation/userOperation.ts
Labels: bug

#618 Enhancement: clear the estimation on remove user request
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
Labels: enhancement

#619 Email vault
  src/controllers/emailVault/emailVault.ts
Labels: bug

#622 Feature: estimation too big flags
  src/controllers/signAccountOp/signAccountOp.ts
Labels: enhancement

#624 Add: userOpHash to SubmittedAccountOp
  src/controllers/activity/activity.ts
  src/controllers/main/main.ts
Labels: bug, enhancement

#625 Feature: fix user op estimation on optimism
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/accountOp/accountOp.ts
  src/libs/gasPrice/gasPrice.ts
  src/libs/userOperation/userOperation.ts
  src/services/bundlers/bundler.ts
  src/services/bundlers/index.ts
Labels: bug, enhancement

#626 Fix: remove portfolio from duplicates
  src/libs/portfolio/portfolio.ts
Labels: bug

#628 Fix: use our estimation for basic accs on optimism
  src/controllers/main/main.ts
  src/libs/gasPrice/gasPrice.ts
Labels: bug

#630 Fix/better optimism erc 4337 estimation
  src/libs/gasPrice/gasPrice.ts
  src/libs/userOperation/userOperation.ts
Labels: bug

#631 Fix/checksum addresses to simulation
  src/controllers/main/main.ts
Labels: bug

#633 Feature: jiffyscan
  src/controllers/activity/activity.ts
  src/services/explorers/jiffyscan.ts
Labels: enhancement

#634 Fix: 4337 activtiy
  src/controllers/activity/activity.ts
Labels: bug

#638 Feature: lower gasUsed for gas tank
  src/libs/estimate/estimate.ts
Labels: enhancement
