Repository AmbireTech/ambire-common, pull requests merged in 2024-11, with the labels that each got.

#1056 add: methods to store a seed temporarily
  src/controllers/keystore/keystore.ts
  src/controllers/main/main.ts
  src/interfaces/banner.ts
Labels: enhancement

#1063 Humanizer: add new legends nft addresses
  src/libs/humanizer/modules/Legends/index.ts
  src/libs/humanizer/modules/Legends/legends.test.ts
  src/libs/humanizer/utils.ts
Labels: enhancement

#1066 Humanizer: legends module fix and add orc warrior
  src/libs/humanizer/modules/Legends/index.ts
Labels: bug, enhancement

#1067 Higher L2 fees
  src/consts/networks.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/estimateHelpers.ts
  src/services/bundlers/bundler.ts
Labels: enhancement

#1069 Fix: token discovery by trace call
  src/libs/tracer/debugTraceCall.ts
Labels: bug

#1073 min 1 gwei for gasPrice
  src/libs/gasPrice/gasPrice.ts
  src/libs/gasPrice/tests/MockProvider.ts
  src/libs/gasPrice/tests/non1559Network.test.ts
Labels: enhancement

#1072 Humanizer: Add methods for socket and aave
  src/interfaces/userRequest.ts
  src/libs/humanizer/const/abis/Aave.ts
  src/libs/humanizer/const/abis/index.ts
  src/libs/humanizer/modules/Aave/aaveV3.ts
  src/libs/humanizer/modules/Aave/aaveWethGatewayV2.ts
  src/libs/humanizer/modules/Aave/index.ts
  src/libs/humanizer/modules/Socket/socketModules.ts
Labels: enhancement

#1065 Feature/paymaster step
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
Labels: enhancement

#1078 Make estimateEOA not required
  src/libs/estimate/estimateEOA.ts
Labels: bug

#1060 Add: hiddenActivityBanners
  src/controllers/activity/activity.ts
  src/interfaces/banner.ts
  src/libs/accountOp/submittedAccountOp.ts
Labels: enhancement

#1083 Fix: infinite estimation
  src/controllers/main/main.ts
Labels: bug

#1085 Humanizer: Aave humanization and humanizerInfo logos update
  scripts/updateHumanizerInfoWithMetaMaskContactMetadata.js
  src/consts/humanizer/humanizerInfo.json
  src/libs/humanizer/modules/Aave/aave.test.ts
  src/libs/humanizer/modules/Aave/aaveLendingPoolV2.ts
  src/libs/humanizer/modules/Aave/aaveV3.ts
  src/libs/humanizer/modules/Aave/aaveWethGatewayV2.ts
Labels: enhancement

#1062 Feature / Defi Positions
  contracts/compiled/AmbireAccount.json
  contracts/compiled/AmbireFactory.json
  contracts/compiled/AmbirePaymaster.json
  contracts/compiled/DeFiAAVEPosition.json
  contracts/compiled/DeFiUniswapV3Positions.json
  contracts/compiled/DeployHelper.json
  contracts/deployless/DeFiAAVEPosition.sol
  contracts/deployless/DeFiUniswapV3Positions.sol
  package-lock.json
  package.json
  src/controllers/defiPositions/defiPositions.test.ts
  src/controllers/defiPositions/defiPositions.ts
  src/controllers/main/main.ts
  src/libs/banners/banners.ts
  src/libs/defiPositions/defiAddresses.ts
  src/libs/defiPositions/defiPositions.test.ts
  src/libs/defiPositions/helpers.ts
  src/libs/defiPositions/providers/aaveV3.ts
  src/libs/defiPositions/providers/helpers/univ3Math.ts
  src/libs/defiPositions/providers/index.ts
  src/libs/defiPositions/providers/uniV3.ts
  src/libs/defiPositions/types.ts
  src/libs/deployless/compile.test.ts
Labels: enhancement

#1079 Humanizer: Humanizer swap and bridge fixes
  src/libs/humanizer/modules/Socket/socket.test.ts
  src/libs/humanizer/modules/Socket/socketModules.ts
Labels: bug

#1081 Feature / SelectedAccountController (PART 1)
  package-lock.json
  src/controllers/accounts/accounts.test.ts
  src/controllers/accounts/accounts.ts
  src/controllers/actions/actions.test.ts
  src/controllers/actions/actions.ts
  src/controllers/activity/activity.test.ts
  src/controllers/activity/activity.ts
  src/controllers/addressBook/addressBook.test.ts
  src/controllers/addressBook/addressBook.ts
  src/controllers/defiPositions/defiPositions.test.ts
  src/controllers/defiPositions/defiPositions.ts
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/selectedAccount/selectedAccount.ts
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/libs/account/account.ts
  test/helpers.ts
Labels: enhancement, refactoring

#1086 Humanizer: add getLink
  src/libs/humanizer/interfaces.ts
  src/libs/humanizer/utils.ts
Labels: enhancement

#1089 Extend / Selected Account Ctrl
  src/controllers/defiPositions/defiPositions.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/selectedAccount/selectedAccount.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/interfaces/selectedAccount.ts
  src/libs/portfolio/index.ts
  src/libs/selectedAccount/selectedAccount.ts
Labels: enhancement, refactoring

#1091 Feature / Enable DeFi Tokens Sending
  src/controllers/selectedAccount/selectedAccount.ts
  src/libs/portfolio/interfaces.ts
  src/libs/selectedAccount/selectedAccount.ts
Labels: enhancement

#1096 Fixes / Portfolio Update Loading State
  src/controllers/main/main.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/selectedAccount/selectedAccount.ts
Labels: bug

#1093 Humanizer: 1inch and deadline update
  src/libs/humanizer/const/abis/1Inch.ts
  src/libs/humanizer/modules/1Inch/index.ts
  src/libs/humanizer/utils.ts
Labels: enhancement

#1097 Refactor/ Portfolio and DeFi state initialization and network data removal
  src/controllers/defiPositions/defiPositions.ts
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
Labels: bug

#1099 add humanizer swap edge case
  src/libs/humanizer/modules/Socket/socketModules.ts
Labels: enhancement

#1074 use eth_gasPrice
  src/libs/gasPrice/gasPrice.ts
Labels: enhancement

#1101 Optimize / Portfolio Banners
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/selectedAccount/selectedAccount.ts
  src/libs/banners/banners.ts
Labels: refactoring

#1106 Add: stETH/wstETH as a fee token
  src/consts/gasTankFeeTokens.ts
  src/controllers/main/main.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.ts
Labels: bug, enhancement

#1103 Fix/ Bug fixes in multiple controllers and UX improvements
  src/controllers/defiPositions/defiPositions.ts
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/selectedAccount/selectedAccount.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug, refactoring

#1108 Bug/ Two `updateAccountState` calls on account import
  src/controllers/main/main.ts
Labels: bug

#1105 Refactoring / DeFi Positions Tokens
  contracts/compiled/DeFiAAVEPosition.json
  contracts/deployless/DeFiAAVEPosition.sol
  src/libs/defiPositions/providers/aaveV3.ts
  src/libs/defiPositions/types.ts
  src/libs/selectedAccount/selectedAccount.ts
Labels: refactoring

#935 Feature: deploy smart contracts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/accountOp/accountOp.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateEOA.ts
  src/libs/gasPrice/gasPrice.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/modules/Deployment/index.ts
  src/libs/portfolio/getOnchainBalances.ts
Labels: bug, enhancement

#1113 Fix: custom networks sign account op
  src/libs/portfolio/portfolio.ts
Labels: bug

#1117 Bug/ Portfolio loading state
  src/controllers/portfolio/portfolio.ts
  src/libs/gasPrice/tests/1559Network.test.ts
  src/libs/gasPrice/tests/non1559Network.test.ts
Labels: bug

#1112 Fix / Resolving of Batched Routes
  src/controllers/main/main.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/libs/banners/banners.ts
Labels: bug

#1110 Feature/4337 ethereum / polygon
  src/consts/networks.ts
  src/controllers/networks/networks.ts
  src/interfaces/network.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/networks/networks.ts
  src/libs/userOperation/userOperation.ts
  src/services/bundlers/bundler.ts
Labels: enhancement

#1124 try to fix the portfolio fee tokens
  src/libs/portfolio/portfolio.ts
Labels: bug

#1127 Fix: disable 4337 for all accounts that aren't on our latest factory
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/userOperation/userOperation.ts
Labels: bug

#1046 Enhancement/ Switch account action
  src/consts/dappCommunication.ts
  src/controllers/actions/actions.ts
  src/controllers/main/main.ts
  src/interfaces/actions.ts
  src/interfaces/userRequest.ts
  src/libs/main/main.ts
Labels: enhancement

#1128 An old account banner warning
  src/controllers/selectedAccount/selectedAccount.ts
  src/interfaces/banner.ts
Labels: enhancement

#1131 Change: rbf condition
  src/controllers/activity/activity.test.ts
  src/controllers/activity/activity.ts
Labels: bug

#1129 bug: significant balance decrease warning when depositing in aave
  src/controllers/main/main.ts
Labels: bug

#1118 Feature / Select Swap & Bridge Token from the Dashboard
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug, enhancement

#1134 Humanizer: Add WTC claim
  src/libs/humanizer/index.ts
  src/libs/humanizer/modules/Airdrops/index.ts
Labels: enhancement

#1137 Feature / Persist Dashboard Network Filter
  src/controllers/selectedAccount/selectedAccount.ts
Labels: enhancement
