Repository AmbireTech/ambire-common, pull requests merged in 2024-06, with the labels that each got.

#779 Config / Enhance Sign & Broadcast Error Handling
  src/controllers/main/main.ts
  src/libs/ledger/ledger.ts
  src/libs/trezor/trezor.ts
Labels: enhancement

#782 Fix: Filter tokenPreferences for total value in portfolio lib
  src/libs/portfolio/portfolio.ts
Labels: bug

#785 EP 0.6.0 Fix: when bundler estimation fails on a custom network's first txn, we did not catch error
  contracts/compiled/AmbireAccountNoRevert.json
  src/libs/estimate/estimate.ts
Labels: bug

#786 Feature/scroll chain
  src/consts/gasTankFeeTokens.ts
  src/consts/networks.ts
  src/controllers/settings/settings.ts
  src/libs/settings/settings.ts
Labels: enhancement

#791 Fix: remove erc4337 settings from networkPreferences for predefined networks only
  src/controllers/settings/settings.ts
Labels: bug

#777 Fix/ Logic around portfolio hints refactoring
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/libs/portfolio/helpers.test.ts
  src/libs/portfolio/helpers.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.ts
Labels: bug

#790 Bug / `dedicatedToOneSA` flag being wrongly set for the internal key iterator
  src/controllers/accountAdder/accountAdder.test.ts
  src/controllers/keystore/keystore.test.ts
  src/interfaces/keystore.ts
  src/libs/account/account.test.ts
  src/libs/account/account.ts
  src/libs/keyIterator/keyIterator.ts
Labels: bug

#796 Fix: portfolio test failing on gasTank isLoading (not awaiting)
  src/controllers/portfolio/portfolio.test.ts
Labels: bug

#795 Bug/ SW warning is displayed for BA
  src/controllers/transfer/transfer.test.ts
  src/controllers/transfer/transfer.ts
  src/interfaces/transfer.ts
Labels: bug

#787 Bug/ validateSendTransferAmount returns success despite error
  src/libs/transfer/amount.ts
  src/libs/transfer/userRequest.ts
  src/services/validations/validate.ts
Labels: bug

#798 Bug / Do not always auto-reset Sign Account OP errors on every update
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#800 Fix / PortfolioVew use Latest instead of Pending with criticalError
  src/libs/portfolio/portfolioView.ts
Labels: bug

#794 Fix/portfolio not removed token
  src/hooks/usePortfolio/usePortfolioFetch/useVelcroFetch.ts
Labels: bug

#802 Fix: do not call coingecko on missing platformId
  src/libs/portfolio/portfolio.ts
Labels: bug

#805 Humanizer: Fix platform id not present in humanizing modules
  src/controllers/signMessage/signMessage.ts
  src/libs/humanizer/humanizerModules.test.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/modules/wrapped.ts
  src/libs/humanizer/parsers/humanizerMetaParsing.ts
  src/libs/humanizer/utils.ts
Labels: bug

#799 Refactoring / SettingsController
  src/consts/coingecko.ts
  src/consts/networks.ts
  src/controllers/accountAdder/accountAdder.ts
  src/controllers/activity/activity.test.ts
  src/controllers/activity/activity.ts
  src/controllers/domains/domains.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/controllers/networks/networks.test.ts
  src/controllers/networks/networks.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/providers/providers.ts
  src/controllers/settings/settings.test.ts
  src/controllers/settings/settings.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/controllers/signMessage/signMessage.test.ts
  src/controllers/signMessage/signMessage.ts
  src/controllers/transfer/transfer.test.ts
  src/controllers/transfer/transfer.ts
  src/interfaces/account.ts
  src/interfaces/banner.ts
  src/interfaces/keystore.ts
  src/interfaces/network.ts
  src/interfaces/provider.ts
  src/interfaces/settings.ts
  src/interfaces/storage.ts
  src/interfaces/transfer.ts
  src/interfaces/userRequest.ts
  src/libs/accountOp/accountOp.ts
  src/libs/accountState/accountState.ts
  src/libs/banners/banners.ts
  src/libs/estimate/customNetworks.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/estimateEOA.ts
  src/libs/estimate/estimateViaEntryPoint.ts
  src/libs/gasPrice/gasPrice.ts
  src/libs/humanizer/interfaces.ts
  src/libs/humanizer/utils.ts
  src/libs/networks/networks.test.ts
  src/libs/networks/networks.ts
  src/libs/portfolio/customToken.ts
  src/libs/portfolio/gecko.ts
  src/libs/portfolio/getNetworksWithAssets.ts
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/helpers.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.ts
  src/libs/portfolio/portfolioView.ts
  src/libs/proxyDeploy/bytecode.ts
  src/libs/signMessage/signMessage.test.ts
  src/libs/signMessage/signMessage.ts
  src/libs/userOperation/userOperation.ts
  src/services/bundlers/bundler.ts
  src/services/ensDomains/ensDomains.ts
  src/services/provider/getRpcProvider.ts
  test/helpers.ts
Labels: refactoring

#806 Bug/ All other networks are removed if portfolio update is called for a single network
  src/controllers/portfolio/portfolio.ts
  src/libs/portfolio/portfolioView.ts
Labels: bug

#811 Fix / Portfolio Race Condition
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
Labels: bug

#812 Fix / Portfolio Race Condition (Part 2)
  src/controllers/portfolio/portfolio.ts
Labels: bug

#814 Fix: add custom network fee option
  src/controllers/networks/networks.ts
Labels: bug

#810 Humanization for Permit2 swap and bug fix
  src/consts/deploy.ts
  src/libs/humanizer/humanizerFuncs.ts
  src/libs/humanizer/humanizerModules.test.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/interfaces.ts
  src/libs/humanizer/modules/Uniswap/Commands.ts
  src/libs/humanizer/modules/Uniswap/uniUnivarsalRouter.ts
  src/libs/humanizer/parsers/humanizerMetaParsing.ts
  src/libs/humanizer/typedMessageModules/erc20Module.ts
  src/libs/humanizer/typedMessageModules/erc721Module.ts
  src/libs/humanizer/typedMessageModules/fallbackModule.ts
  src/libs/humanizer/typedMessageModules/permit2Module.ts
Labels: bug, enhancement

#813 Migrate / DappsController to ambire-common
  src/classes/session.ts
  src/consts/dappCatalog.json
  src/controllers/dapps/dapps.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/interfaces/messenger.ts
Labels: refactoring

#816 Fix / Portfolio Additional Assigning critical Error On empty error object
  src/controllers/portfolio/portfolio.ts
Labels: bug

#818 Humanizer: file structure
  src/interfaces/humanizer.ts
  src/interfaces/userRequest.ts
  src/libs/accountOp/accountOp.ts
  src/libs/humanizer/humanizerFuncs.test.ts
  src/libs/humanizer/humanizerFuncs.ts
  src/libs/humanizer/humanizerModules.test.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/interfaces.ts
  src/libs/humanizer/lazyStorage.test.ts
  src/libs/humanizer/lazyStorage.ts
  src/libs/humanizer/modules/Aave/aave.test.ts
  src/libs/humanizer/modules/FallbackHumanizer/fallBackHumanizer.ts
  src/libs/humanizer/modules/FallbackHumanizer/fallbackHumanizer.test.ts
  src/libs/humanizer/modules/FallbackHumanizer/index.ts
  src/libs/humanizer/modules/GasTankModule/gasTank.test.ts
  src/libs/humanizer/modules/GasTankModule/gasTankModule.ts
  src/libs/humanizer/modules/GasTankModule/index.ts
  src/libs/humanizer/modules/PreProcess/index.ts
  src/libs/humanizer/modules/PreProcess/preProcessModule.ts
  src/libs/humanizer/modules/Privileges/index.ts
  src/libs/humanizer/modules/Privileges/privileges.test.ts
  src/libs/humanizer/modules/Privileges/privileges.ts
  src/libs/humanizer/modules/Sushiswap/index.ts
  src/libs/humanizer/modules/Sushiswap/sushiSwapModule.ts
  src/libs/humanizer/modules/Sushiswap/sushiswap.test.ts
  src/libs/humanizer/modules/Tokens/index.ts
  src/libs/humanizer/modules/Tokens/tokens.test.ts
  src/libs/humanizer/modules/Tokens/tokens.ts
  src/libs/humanizer/modules/Uniswap/index.ts
  src/libs/humanizer/modules/Uniswap/interfaces.ts
  src/libs/humanizer/modules/Uniswap/uniUniversalRouter.ts
  src/libs/humanizer/modules/Uniswap/uniV2.ts
  src/libs/humanizer/modules/Uniswap/uniV3.ts
  src/libs/humanizer/modules/Uniswap/uniswap.test.ts
  src/libs/humanizer/modules/WALLET/wallet.test.ts
  src/libs/humanizer/modules/Wrapping/index.ts
  src/libs/humanizer/modules/Wrapping/wrapping.test.ts
  src/libs/humanizer/modules/Wrapping/wrapping.ts
  src/libs/humanizer/modules/oneInch.ts
  src/libs/humanizer/utils.ts
Labels: documentation, refactoring

#820 Bug/ `withStatus` not working with minification
  src/controllers/emailVault/emailVault.ts
  src/controllers/keystore/keystore.ts
  src/controllers/main/main.ts
  src/controllers/networks/networks.ts
Labels: bug

#821 Fix / Not Full Tokens List On Cached Data
  src/hooks/usePortfolio/usePortfolioFetch/useVelcroFetch.ts
Labels: bug

#817 Refactoring / Accounts
  src/consts/account.ts
  src/controllers/accountAdder/accountAdder.test.ts
  src/controllers/accountAdder/accountAdder.ts
  src/controllers/accounts/accounts.test.ts
  src/controllers/accounts/accounts.ts
  src/controllers/actions/actions.test.ts
  src/controllers/actions/actions.ts
  src/controllers/activity/activity.test.ts
  src/controllers/activity/activity.ts
  src/controllers/addressBook/addressBook.test.ts
  src/controllers/addressBook/addressBook.ts
  src/controllers/eventEmitter/eventEmitter.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/settings/settings.test.ts
  src/controllers/settings/settings.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/controllers/signMessage/signMessage.test.ts
  src/controllers/transfer/transfer.test.ts
  src/interfaces/account.ts
  src/interfaces/settings.ts
  src/libs/account/account.test.ts
  src/libs/account/account.ts
  src/libs/accountState/accountState.test.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimateBundler.test.ts
  src/libs/humanizer/index.test.ts
  src/libs/portfolio/portfolio.test.ts
  src/libs/signMessage/signMessage.test.ts
  src/libs/userOperation/userOperation.test.ts
  src/services/bundlers/bundler.test.ts
  test/config.ts
  test/helpers.ts
Labels: refactoring

#826 Improvements / updateSelectedAccount
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
Labels: refactoring

#828 Bug / Updating account preferences failing in the PROD build
  src/controllers/accounts/accounts.ts
Labels: bug

#819 Humanizer modules: curve, trader joe, across, kyberswap, 1inch
  src/libs/humanizer/const/abis/1Inch.ts
  src/libs/humanizer/const/abis/Across.ts
  src/libs/humanizer/const/abis/Curve.ts
  src/libs/humanizer/const/abis/KyberSwap.ts
  src/libs/humanizer/const/abis/TraderJoe.ts
  src/libs/humanizer/const/abis/index.ts
  src/libs/humanizer/humanizerFuncs.ts
  src/libs/humanizer/humanizerModules.test.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/interfaces.ts
  src/libs/humanizer/modules/1Inch/1inch.test.ts
  src/libs/humanizer/modules/1Inch/index.ts
  src/libs/humanizer/modules/Across/across.test.ts
  src/libs/humanizer/modules/Across/index.ts
  src/libs/humanizer/modules/Curve/curve.test.ts
  src/libs/humanizer/modules/Curve/index.ts
  src/libs/humanizer/modules/KyberSwap/index.ts
  src/libs/humanizer/modules/KyberSwap/kyberSwap.test.ts
  src/libs/humanizer/modules/Privileges/privileges.test.ts
  src/libs/humanizer/modules/TraderJoe/index.ts
  src/libs/humanizer/modules/TraderJoe/traderjoe.test.ts
  src/libs/humanizer/modules/Wrapping/wrapping.test.ts
  src/libs/humanizer/modules/Wrapping/wrapping.ts
  src/libs/humanizer/testHelpers.ts
  src/libs/humanizer/utils.ts
Labels: bug

#832 Extra const networks
  src/consts/networks.ts
Labels: enhancement

#825 Improvements / Simulation
  src/controllers/main/main.ts
  src/libs/account/account.ts
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolioView.ts
Labels: refactoring

#835 Add: BroadcastButStuck transaction status
  src/controllers/activity/activity.ts
  src/libs/accountOp/accountOp.ts
Labels: enhancement
