Repository AmbireTech/ambire-common, pull requests merged in 2025-01, with the labels that each got.

#1192 Fix / Sign AmbireOperation TypedData Message
  src/controllers/main/main.ts
Labels: bug

#1196 Fix: sponsorship for the correct user req
  src/consts/addresses.ts
  src/libs/main/main.ts
  src/libs/portfolio/portfolio.test.ts
Labels: bug

#1195 Feature/ambire readable operation
  src/interfaces/hex.ts
  src/libs/signMessage/signMessage.test.ts
  src/libs/signMessage/signMessage.ts
  src/utils/isSameAddr.ts
Labels: enhancement

#1197 Humanizer: fix some hardcoded function selectors
  src/consts/humanizer/dappSelectors.json
  src/consts/humanizer/humanizerInfo.json
Labels: bug

#1194 Humanizer: hidden calls inside a call to the current account
  src/libs/humanizer/const/abis/AmbireAccount.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/modules/embeddedAmbireOperationHumanizer/ambireOperation.test.ts
  src/libs/humanizer/modules/embeddedAmbireOperationHumanizer/index.ts
Labels: enhancement

#1198 Min 10$ balance to use the gas tank
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
Labels: enhancement

#1199 Humanizer: fix recursively hidden calls inside execute calls explot
  src/libs/humanizer/modules/embeddedAmbireOperationHumanizer/ambireOperation.test.ts
  src/libs/humanizer/modules/embeddedAmbireOperationHumanizer/index.ts
Labels: bug, enhancement

#1203 Enhancement/ Get aave3 positions on scroll (defi positions)
  src/libs/defiPositions/defiAddresses.ts
Labels: enhancement

#1204 Fix/ Significant balance decrease warning doesn't count hidden tokens
  src/controllers/signAccountOp/helper.ts
  src/libs/portfolio/helpers.ts
Labels: bug

#1190 Enhancement/ Improve portfolio error banner UX
  src/controllers/defiPositions/defiPositions.test.ts
  src/controllers/defiPositions/defiPositions.ts
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/selectedAccount/selectedAccount.ts
  src/libs/banners/banners.ts
  src/libs/defiPositions/providers/aaveV3.ts
  src/libs/defiPositions/providers/helpers/networksWithPositions.ts
  src/libs/defiPositions/types.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.ts
Labels: enhancement

#1205 Humanizer: ENS
  src/libs/humanizer/const/coinType.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/messageModules/ensModule.ts
  src/libs/humanizer/modules/ENS/index.ts
  src/libs/humanizer/utils.ts
Labels: enhancement

#1200 Feature/biconomy
  src/consts/bundlers.ts
  src/consts/networks.ts
  src/controllers/main/main.ts
  src/controllers/networks/networks.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/interfaces/network.ts
  src/libs/accountOp/submittedAccountOp.ts
  src/libs/erc7677/types.ts
  src/libs/errorDecoder/customErrors.ts
  src/libs/errorDecoder/errorDecoder.ts
  src/libs/errorDecoder/handlers/biconomy.ts
  src/libs/errorDecoder/handlers/innerCallFailure.ts
  src/libs/errorDecoder/handlers/pimlico.ts
  src/libs/errorHumanizer/broadcastErrorHumanizer.ts
  src/libs/errorHumanizer/errors.ts
  src/libs/errorHumanizer/estimationErrorHumanizer.ts
  src/libs/errorHumanizer/helpers.ts
  src/libs/errorHumanizer/humanizeCommonCases.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.test.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/interfaces.ts
  src/libs/paymaster/abstractPaymaster.ts
  src/libs/paymaster/paymaster.ts
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/signMessage/signMessage.test.ts
  src/libs/signMessage/signMessage.ts
  src/libs/userOperation/types.ts
  src/libs/userOperation/userOperation.test.ts
  src/libs/userOperation/userOperation.ts
  src/services/bundlers/DevBundlerSwitcher.ts
  src/services/bundlers/biconomy.ts
  src/services/bundlers/brokenBiconomyBroadcast.ts
  src/services/bundlers/brokenPimlicoBroadcast.ts
  src/services/bundlers/bundler.test.ts
  src/services/bundlers/bundler.ts
  src/services/bundlers/bundlerSwitcher.test.ts
  src/services/bundlers/bundlerSwitcher.ts
  src/services/bundlers/getBundler.ts
  src/services/bundlers/index.ts
  src/services/bundlers/pimlico.ts
  src/services/bundlers/types.ts
  src/services/paymaster/PaymasterFactory.ts
  src/utils/benzin.ts
Labels: enhancement

#1215 Humanizer: more Lido methods
  src/libs/humanizer/const/abis/Lido.ts
  src/libs/humanizer/modules/Lido/index.ts
Labels: enhancement

#1217 Humanizer: add 1 Aave address /w meta & fix some aave texts
  src/consts/humanizer/humanizerInfo.json
  src/libs/humanizer/modules/Aave/aave.test.ts
  src/libs/humanizer/modules/Aave/aaveLendingPoolV2.ts
  src/libs/humanizer/modules/Aave/aaveWethGatewayV2.ts
Labels: enhancement

#1218 Fix / Open Next Action After Resolving a SwitchAccount Action
  src/controllers/main/main.ts
Labels: bug

#1212 Humanizer: Opensea humanizer
  src/libs/humanizer/index.ts
  src/libs/humanizer/messageModules/index.ts
  src/libs/humanizer/messageModules/openseaModule.ts
  src/libs/humanizer/modules/OpenSea/index.ts
Labels: enhancement

#1221 Fix: activity.ts user op failure
  src/controllers/activity/activity.ts
  src/libs/userOperation/types.ts
  src/libs/userOperation/userOperation.ts
Labels: bug

#1226 Slower intervals
  src/controllers/activity/activity.ts
  src/controllers/main/main.ts
Labels: enhancement

#1227 Feature / Swap & Bridge Refresh Routes Button
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: enhancement

#1224 Fix/insufficient native report
  src/controllers/main/main.test.ts
  src/libs/errorDecoder/customErrors.ts
  src/libs/errorDecoder/errorDecoder.test.ts
  src/libs/errorDecoder/handlers/innerCallFailure.ts
  src/libs/errorHumanizer/errors.ts
  src/libs/errorHumanizer/helpers.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
Labels: enhancement

#1229 Update/ Message when SAs are supported but contracts aren't deployed
  src/libs/networks/networks.ts
Labels: enhancement

#1230 Fix / Swap & Bridge Route Prepare Returns Status 500
  src/controllers/main/main.ts
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug

#1222 Humanizer: minor updates
  src/libs/humanizer/const/abis/Legends.ts
  src/libs/humanizer/const/abis/Tokens.ts
  src/libs/humanizer/modules/Legends/index.ts
  src/libs/humanizer/modules/Tokens/tokens.ts
Labels: enhancement

#1233 Actions Fixes And Improvements
  src/controllers/actions/actions.test.ts
  src/controllers/actions/actions.ts
  src/controllers/main/main.ts
  src/libs/actions/actions.ts
  src/libs/main/main.ts
Labels: bug, refactoring

#1232 Fix / Resize and Reposition Action Window on Focus
  src/controllers/accountAdder/accountAdder.test.ts
  src/controllers/actions/actions.test.ts
  src/controllers/actions/actions.ts
  src/controllers/emailVault/emailVault.test.ts
  src/controllers/keystore/keystore.test.ts
  src/controllers/main/main.test.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signMessage/signMessage.test.ts
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/interfaces/window.ts
  src/libs/signMessage/signMessage.test.ts
Labels: bug

#1236 Fix / Swap & Bridge Freeze on Loading Screen
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/services/socket/api.ts
Labels: bug

#1241 Humanizer: swap amounts and texts
  src/libs/humanizer/modules/Socket/socketModules.ts
  src/libs/humanizer/modules/TraderJoe/index.ts
  src/libs/humanizer/modules/TraderJoe/traderjoe.test.ts
  src/libs/humanizer/modules/Uniswap/uniUniversalRouter.ts
  src/libs/humanizer/modules/Uniswap/uniV2.ts
  src/libs/humanizer/modules/Uniswap/uniV3.ts
  src/libs/humanizer/modules/Uniswap/uniswap.test.ts
  src/libs/humanizer/testHelpers.ts
Labels: enhancement

#1225 Fix / flatten and move all tokens into one array after pagination
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/pagination.ts
  src/libs/portfolio/portfolio.ts
Labels: bug

#1238 stkWallet: add stakeAndWrap and innetMint methods
  contracts/stkWALLET.sol
  scripts/deployStkWallet.ts
  test/stkWallet/stkWallet.ts
Labels: enhancement

#1245 Fix / pass additional portfolio tokens to array in calculating account portfolio
  src/libs/selectedAccount/selectedAccount.ts
Labels: bug

#1247 The sponsorship fallback was broken for accounts that didn't have any native
  src/controllers/signAccountOp/signAccountOp.ts
  src/services/bundlers/bundler.test.ts
Labels: bug

#1249 Humanizer: stkWALLET and entry point additions
  src/consts/addresses.ts
  src/libs/humanizer/const/abis/stkWallet.ts
  src/libs/humanizer/humanizeMessages.test.ts
  src/libs/humanizer/messageModules/entryPointModule.ts
  src/libs/humanizer/modules/WALLET/index.ts
Labels: enhancement

#1252 Humanizer: swap amount out one more case
  src/libs/humanizer/humanizeMessages.test.ts
  src/libs/humanizer/modules/Socket/socketModules.ts
Labels: bug, enhancement

#1250 Bug/ Selected account portfolio tokens will be missing if there is no pending state
  src/libs/selectedAccount/selectedAccount.ts
Labels: bug

#1100 Add / Pending balance delta threshold
  src/libs/portfolio/pendingAmountsHelper.ts
Labels: bug

#1242 Enhancement/ Update balance errors ux
  src/controllers/accounts/accounts.test.ts
  src/controllers/accounts/accounts.ts
  src/controllers/main/main.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/selectedAccount/selectedAccount.ts
  src/interfaces/banner.ts
  src/libs/banners/banners.ts
  src/libs/selectedAccount/errors.ts
Labels: enhancement

#1256 Fix / Action Windows Race Condition
  src/controllers/actions/actions.ts
Labels: bug

#1258 Main controller: method for deleting individual calls
  src/controllers/actions/actions.ts
  src/controllers/main/main.ts
  src/interfaces/userRequest.ts
  src/libs/accountOp/types.ts
Labels: enhancement

#1260 Feature / Action Window Track Focused State
  src/controllers/accountAdder/accountAdder.test.ts
  src/controllers/actions/actions.test.ts
  src/controllers/actions/actions.ts
  src/controllers/emailVault/emailVault.test.ts
  src/controllers/keystore/keystore.test.ts
  src/controllers/main/main.test.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signMessage/signMessage.test.ts
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/interfaces/window.ts
  src/libs/signMessage/signMessage.test.ts
Labels: enhancement

#1266 Fix / Extension Crashing Upon Network Removal
  src/controllers/selectedAccount/selectedAccount.ts
  src/libs/selectedAccount/errors.ts
Labels: bug

#1264 Humanizer: Socket executeController wrapper handling
  src/libs/humanizer/const/abis/socket.ts
  src/libs/humanizer/modules/Socket/socketModules.ts
Labels: enhancement

#1267 Fix / Deployless - Out of gas
  src/libs/portfolio/portfolio.ts
Labels: bug

#1257 Enhancement/ Refactor token preferences
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/libs/portfolio/customToken.ts
  src/libs/portfolio/helpers.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/migrations/tokenPreferences.test.ts
  src/libs/portfolio/migrations/tokenPreferences.ts
  src/libs/portfolio/portfolio.ts
Labels: refactoring

#1271 Humanizer: Aave `withdraw(bytes32)` case
  src/libs/humanizer/modules/Aave/aaveV3.ts
Labels: enhancement

#1272 Humanizer: socket
  src/libs/humanizer/const/abis/socket.ts
  src/libs/humanizer/modules/Socket/socketModules.ts
Labels: enhancement

#1268 Rename / Open chest to unlock chest humanization
  src/libs/humanizer/modules/Legends/index.ts
Labels: enhancement
