Repository AmbireTech/ambire-common, pull requests merged in 2025-07, with the labels that each got.

#1571 Fix / Resolve AddChain dapp request on window close
  src/controllers/actions/actions.test.ts
  src/controllers/actions/actions.ts
  src/controllers/main/main.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/swapAndBridge/swapAndBridge.test.ts
Labels: bug

#1570 No bridges for sa to networks that do not support sa
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: enhancement

#1574 signMessage: fix encoding of dynamic arrays in EIP-712
  src/libs/signMessage/signMessage.ts
Labels: bug

#1579 Rewards NFT: allow unminted tokens to have URI
  contracts/rewardsNftImplementation.sol
  test/RewardsNft/rewardsNft.ts
Labels: enhancement

#1573 Fix: calling cena on every portfolio update for tokens without price
  src/libs/portfolio/portfolio.ts
Labels: bug

#1580 Feature/user ops nonces
  src/controllers/estimation/estimation.ts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/controllers/signAccountOp/signAccountOpTester.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/controllers/transfer/transfer.test.ts
  src/controllers/transfer/transfer.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/userOperation/userOperation.ts
  src/services/bundlers/types.ts
Labels: bug, enhancement

#1584 Remove rbf check in activity
  src/controllers/activity/activity.test.ts
  src/controllers/activity/activity.ts
Labels: bug

#1581 Add: fetch an unique nonce id from the base account
  src/controllers/defiPositions/defiPositions.ts
  src/libs/account/BaseAccount.ts
  src/libs/account/EOA.ts
  src/libs/account/EOA7702.ts
  src/libs/account/V1.ts
  src/libs/account/V2.ts
Labels: enhancement

#1585 Check if a bundler is implemented in the codebase
  src/services/bundlers/bundler.ts
  src/services/bundlers/bundlerSwitcher.ts
  src/services/bundlers/getAvailableBundlers.ts
  src/services/bundlers/getBundler.ts
  src/services/bundlers/getBundlerByName.ts
Labels: enhancement

#1587 Fix/ Account label flickering between states on rename
  src/controllers/accounts/accounts.test.ts
  src/controllers/accounts/accounts.ts
Labels: bug

#1594 Remove jiffyscan
  src/services/explorers/jiffyscan.ts
Labels: enhancement

#1593 Fix: deployless token mapping
  src/libs/portfolio/getOnchainBalances.ts
Labels: bug

#1596 Improve / Initial Loading Performance + Portfolio Improvements
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/selectedAccount/selectedAccount.ts
  src/libs/selectedAccount/errors.ts
  src/libs/selectedAccount/selectedAccount.ts
Labels: bug, refactoring

#1592 Config / Activate api key for our Swap & Bridge service provider (LiFi) when we hit the rate limit #5055
  src/controllers/main/main.ts
  src/interfaces/fetch.ts
  src/services/lifi/api.ts
Labels: enhancement

#1608 Feature/gelato
  src/consts/bundlers.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/errorHumanizer/broadcastErrorHumanizer.ts
  src/libs/errorHumanizer/errors.ts
  src/libs/paymaster/abstractPaymaster.ts
  src/libs/paymaster/paymaster.ts
  src/libs/userOperation/userOperation.ts
  src/services/bundlers/gelato.ts
  src/services/bundlers/getBundler.ts
Labels: enhancement

#1609 Bundler lottery system
  src/libs/estimate/estimateBundler.test.ts
  src/services/bundlers/DevBundlerSwitcher.ts
  src/services/bundlers/bundlerSwitcher.test.ts
  src/services/bundlers/getBundler.ts
Labels: enhancement

#1613 Fix/ Selected account defi positions calculations
  src/libs/defiPositions/types.ts
  src/libs/selectedAccount/selectedAccount.ts
Labels: bug

#1615 Fix: sponsorship on bundler lottery
  src/libs/erc7677/erc7677.ts
Labels: bug

#1626 Fix / Transfer - Skip tracking on close
  src/controllers/main/main.ts
  src/controllers/transfer/transfer.ts
Labels: bug

#1631 Fix/ defi position value mistakenly excluded in selectedAccount lib
  src/libs/selectedAccount/selectedAccount.ts
Labels: bug

#1624 Feature / Requests Controller
  src/controllers/accounts/accounts.ts
  src/controllers/keystore/keystore.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/controllers/requests/requests.test.ts
  src/controllers/requests/requests.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/selectedAccount/selectedAccount.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/interfaces/requests.ts
  src/libs/main/main.ts
  src/libs/requests/requests.ts
  src/libs/selectedAccount/selectedAccount.test.ts
  src/libs/selectedAccount/selectedAccount.ts
Labels: enhancement, refactoring
