Repository AmbireTech/ambire-common, pull requests merged in 2025-04, with the labels that each got.

#1401 Remove the lifi key from the front end
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/services/lifi/api.ts
Labels: bug

#1402 Fix: make a portfolio update after a successfull bridge
  src/controllers/main/main.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug

#1404 Fix/ Error decoder formats custom contract error to an invalid utf8 string and breaks humanization
  src/libs/errorDecoder/errorDecoder.test.ts
  src/libs/errorDecoder/helpers.test.ts
  src/libs/errorDecoder/helpers.ts
Labels: bug

#1405 Humanizer: add case for squashing two swap calls
  src/libs/humanizer/modules/Uniswap/index.ts
  src/libs/humanizer/modules/Uniswap/uniswap.test.ts
  src/libs/humanizer/modules/Uniswap/utils.ts
Labels: enhancement

#1406 Humanizer:refactor permit2 humanization logic
  src/consts/addresses.ts
  src/libs/humanizer/humanizeMessages.test.ts
  src/libs/humanizer/index.test.ts
  src/libs/humanizer/messageModules/erc20Module.ts
  src/libs/humanizer/messageModules/permit2Module.ts
  src/libs/humanizer/modules/Uniswap/uniswap.test.ts
  src/libs/humanizer/modules/Uniswap/utils.ts
Labels: enhancement

#1374 Refactor/estimate controller
  src/controllers/estimation/estimation.ts
  src/controllers/estimation/types.ts
  src/controllers/gasPrice/gasPrice.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/providers/providers.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/controllers/signAccountOp/signAccountOpTester.ts
  src/interfaces/network.ts
  src/libs/account/BaseAccount.ts
  src/libs/account/EOA.ts
  src/libs/account/EOA7702.ts
  src/libs/account/V1.ts
  src/libs/account/V2.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.test.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/interfaces.ts
  src/libs/paymaster/abstractPaymaster.ts
  src/libs/paymaster/paymaster.ts
  src/services/bundlers/DevBundlerSwitcher.ts
  src/services/bundlers/bundlerSwitcher.test.ts
  src/services/bundlers/bundlerSwitcher.ts
  src/utils/networks.ts
  src/utils/timeout.ts
Labels: enhancement

#1408 Feature / Transfer - Popup and Tab support
  src/controllers/transfer/transfer.test.ts
  src/controllers/transfer/transfer.ts
Labels: enhancement

#1410 Remove one time nonce implementation
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/portfolio/portfolio.test.ts
  src/libs/userOperation/userOperation.test.ts
  src/libs/userOperation/userOperation.ts
Labels: refactoring

#1409 Humanizer: add basic Guild and Pancake approve humanizer
  src/libs/humanizer/const/abis/Guild.ts
  src/libs/humanizer/const/abis/Pancake.ts
  src/libs/humanizer/index.ts
  src/libs/humanizer/modules/Guild/Guild.test.ts
  src/libs/humanizer/modules/Guild/index.ts
  src/libs/humanizer/modules/Pancake/Pancake.test.ts
  src/libs/humanizer/modules/Pancake/index.ts
Labels: enhancement

#1411 Fix: double init of sign account op
  src/controllers/main/main.ts
Labels: bug

#1412 Fix: pass the correct data to pm_getStubData
  src/libs/estimate/estimateBundler.ts
Labels: bug

#1413 Feature/retry on underpriced
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/paymaster/abstractPaymaster.ts
  src/libs/paymaster/paymaster.ts
Labels: bug, enhancement

#1373 Update/ Replace `isDefiToken` flag with `defiTokenType`
  src/controllers/signAccountOp/helper.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/interfaces/assets.ts
  src/libs/defiPositions/helpers.ts
  src/libs/defiPositions/types.ts
  src/libs/portfolio/index.ts
  src/libs/portfolio/interfaces.ts
  src/libs/selectedAccount/selectedAccount.ts
Labels: bug

#1415 Fix/faster next broadcast
  src/controllers/accounts/accounts.ts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/errorHumanizer/broadcastErrorhumanizer.test.ts
  src/libs/errorHumanizer/errors.ts
Labels: bug, enhancement

#1417 Fix: always load the network icons from the relayer
  src/controllers/networks/networks.ts
Labels: bug

#1419 Add: new fee tokens
  src/consts/gasTankFeeTokens.ts
Labels: enhancement

#1418 Relayer record EOA transaction
  src/controllers/main/main.ts
Labels: enhancement

#1422 Feature/7702 gas tank
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/libs/account/EOA7702.ts
  src/libs/portfolio/helpers.ts
Labels: enhancement

#1426 Update / legends data in dapp catalog
  src/consts/dappCatalog.json
  src/consts/dappCommunication.ts
  src/controllers/dapps/dapps.ts
Labels: refactoring

#1432 add: init code for the deploy on stub data request
  src/libs/estimate/estimateBundler.ts
  src/libs/paymaster/abstractPaymaster.ts
  src/libs/paymaster/paymaster.ts
  src/services/paymaster/PaymasterFactory.ts
Labels: bug

#1398 Feature / New Onboarding Flow
  src/README.md
  src/consts/derivation.ts
  src/consts/hardwareWallets.ts
  src/controllers/accountAdder/accountAdder.test.ts
  src/controllers/accountPicker/accountPicker.test.ts
  src/controllers/accountPicker/accountPicker.ts
  src/controllers/accounts/accounts.ts
  src/controllers/activity/activity.ts
  src/controllers/emailVault/emailVault.ts
  src/controllers/keystore/keystore.test.ts
  src/controllers/keystore/keystore.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/interfaces/banner.ts
  src/interfaces/keyIterator.ts
  src/interfaces/keystore.ts
  src/libs/accountPicker/accountPicker.ts
  src/libs/keyIterator/keyIterator.ts
  src/libs/keys/keys.ts
  src/services/validations/validate.ts
Labels: enhancement

#1434 Enable 7702 sponsorships
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/account/BaseAccount.ts
  src/libs/account/EOA7702.ts
  src/libs/paymaster/paymaster.ts
Labels: enhancement

#1444 Humanizer: stkWALLET addr and humanizer
  src/consts/addresses.ts
  src/libs/humanizer/modules/WALLET/WALLETSupplyController.ts
  src/libs/humanizer/modules/WALLET/wallet.test.ts
Labels: enhancement
