Repository AmbireTech/ambire-common, pull requests merged in 2025-06, with the labels that each got.

#1516 Rename benzin to explorer
  src/controllers/activity/activity.ts
Labels: enhancement

#1517 Handle swap & bridge estimation failures in the controller
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: enhancement

#1522 Fix: show account native or EOA native if EOA has some
  src/libs/account/V1.ts
  src/libs/account/V2.ts
Labels: bug

#1523 Enable route selection even if 1 to enable people to see extra info
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: enhancement

#1521 Show the paymaster error if returned
  src/controllers/phishing/phishing.test.ts
  src/controllers/phishing/phishing.ts
  src/libs/errorDecoder/customErrors.ts
  src/libs/errorDecoder/errorDecoder.test.ts
  src/libs/errorHumanizer/broadcastErrorHumanizer.ts
  src/libs/errorHumanizer/broadcastErrorhumanizer.test.ts
  src/libs/errorHumanizer/estimationErrorHumanizer.ts
  src/libs/errorHumanizer/helpers.ts
  src/libs/errorHumanizer/humanizeCommonCases.test.ts
  src/libs/errorHumanizer/humanizeCommonCases.ts
  src/libs/paymaster/paymaster.ts
  src/libs/relayerCall/relayerCall.ts
Labels: bug

#1527 Fix: EOA batch order
  src/controllers/main/main.ts
Labels: bug

#1535 UX/ Swap state consistency, UI responsiveness and error handling
  src/classes/SwapAndBridgeProviderApiError.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/libs/accountOp/accountOp.ts
  src/services/lifi/api.ts
  src/services/lifi/consts.ts
  src/services/lifi/helpers.ts
Labels: enhancement, refactoring

#1537 Fix: Celo chain LiFi
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/libs/swapAndBridge/swapAndBridge.ts
  src/services/lifi/api.ts
Labels: enhancement

#1549 Humanizer: add snapshot voting
  src/libs/humanizer/index.ts
  src/libs/humanizer/messageModules/index.ts
  src/libs/humanizer/messageModules/snapshotModule.ts
Labels: enhancement

#1550 Fixes / Bypass DeBank DeFi Call in Testing Mode
  src/controllers/defiPositions/defiPositions.test.ts
  src/controllers/defiPositions/defiPositions.ts
Labels: bug

#1553 Refetch on rejected
  src/libs/accountOp/submittedAccountOp.ts
Labels: bug

#1557 Optimizations / DeFi Positions
  src/consts/intervals.ts
  src/controllers/defiPositions/defiPositions.ts
  src/controllers/main/main.ts
  src/libs/selectedAccount/selectedAccount.ts
Labels: bug, refactoring

#1556 Force update the activity on account change
  src/controllers/main/main.ts
Labels: bug

#1562 Fixes / Window Positioning on Create Based on the Parent Window
  src/classes/session.ts
  src/controllers/actions/actions.test.ts
  src/controllers/actions/actions.ts
  src/controllers/dapps/dapps.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/interfaces/userRequest.ts
  src/interfaces/window.ts
  src/libs/dapps/helpers.ts
  src/libs/swapAndBridge/swapAndBridge.ts
  src/libs/transfer/userRequest.ts
  test/helpers/window.ts
Labels: bug

#1564 Fix / DeFi positions network filter not working
  src/controllers/defiPositions/defiPositions.ts
Labels: bug

#1563 Feature/etherspot
  src/consts/bundlers.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/account/BaseAccount.ts
  src/libs/account/EOA7702.ts
  src/libs/errorDecoder/errorDecoder.ts
  src/libs/errorDecoder/handlers/etherspot.ts
  src/libs/errorHumanizer/errors.ts
  src/libs/estimate/interfaces.ts
  src/services/bundlers/bundler.ts
  src/services/bundlers/bundlerSwitcher.ts
  src/services/bundlers/etherspot.ts
  src/services/bundlers/getBundler.ts
Labels: enhancement

#1568 bundler switch on 7702
  src/controllers/main/main.ts
  src/libs/account/BaseAccount.ts
  src/libs/account/EOA7702.ts
  src/libs/accountOp/submittedAccountOp.ts
  src/libs/errorDecoder/handlers/biconomy.ts
  src/libs/errorDecoder/handlers/etherspot.ts
  src/libs/errorDecoder/handlers/pimlico.ts
  src/libs/estimate/estimateBundler.ts
  src/services/bundlers/bundlerSwitcher.test.ts
  src/services/bundlers/bundlerSwitcher.ts
  src/services/bundlers/getBundler.ts
Labels: enhancement

#1560 Swap&Bridge retry mechanism
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/libs/swapAndBridge/swapAndBridge.ts
  src/services/lifi/api.ts
Labels: enhancement
