Repository AmbireTech/ambire-common, pull requests merged in 2025-05, with the labels that each got.

#1448 Enable 7702 for Gnosis
  src/consts/7702.ts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/estimate/estimateBundler.ts
  src/services/bundlers/bundlerSwitcher.ts
  src/services/bundlers/getBundler.ts
Labels: enhancement

#1451 Performance: sooner debug trace call
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
Labels: enhancement

#1447 Feature / Manage Recovery Phrases
  src/controllers/accountPicker/accountPicker.ts
  src/controllers/keystore/keystore.ts
Labels: enhancement

#1445 Sponsored Gnosis
  src/controllers/main/main.ts
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/libs/account/BaseAccount.ts
  src/libs/account/EOA7702.ts
  src/libs/account/V2.ts
  src/libs/erc7677/erc7677.ts
  src/libs/erc7677/types.ts
  src/libs/swapAndBridge/swapAndBridge.ts
  src/libs/transfer/userRequest.ts
Labels: enhancement

#1453 Fix/swap and bridge bugs and improvements
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug, enhancement

#1456 Feature/send calls v2
  src/controllers/activity/activity.ts
  src/controllers/main/main.ts
  src/libs/5792/5792.ts
  src/libs/account/BaseAccount.ts
  src/libs/account/EOA.ts
  src/libs/account/EOA7702.ts
  src/libs/account/V1.ts
  src/libs/account/V2.ts
  src/libs/accountOp/accountOp.ts
  src/libs/main/main.ts
  src/libs/portfolio/portfolio.test.ts
Labels: enhancement

#1458 Fix: select the next route on step txn failure
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/libs/tracer/debugTraceCall.test.ts
Labels: bug

#1423 Add/ `isWeb3App` flag to dapp sessions
  src/classes/session.ts
  src/controllers/dapps/dapps.ts
Labels: enhancement

#1466 Fix/ Swap doesn't use the latest `fromSelectedToken` amounts
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug

#1463 Feature / Associate Account Keys with the Legacy Saved Seed
  src/controllers/accountPicker/accountPicker.ts
  src/controllers/defiPositions/defiPositions.test.ts
  src/controllers/defiPositions/defiPositions.ts
  src/controllers/keystore/keystore.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/storage/storage.ts
Labels: enhancement, refactoring

#1443 Allow velcro fetch for custom networks
  src/controllers/portfolio/portfolio.test.ts
  src/libs/portfolio/portfolio.ts
  src/libs/tracer/debugTraceCall.test.ts
Labels: enhancement

#1470 Filter disabledByDefault relayer networks
  src/controllers/networks/networks.ts
  src/interfaces/network.ts
Labels: configuration

#1469 Legends: add bnb addresses for aave and uniswap in defi constants
  src/libs/defiPositions/defiAddresses.ts
Labels: enhancement

#1475 Defi positions: hardcode addresses for some custom chains for defi positions
  src/libs/defiPositions/defiAddresses.ts
Labels: enhancement

#1476 Fix / loss of keys after execution of the legacy saved seed migration
  src/controllers/storage/storage.ts
Labels: bug

#1477 Refactoring / Smaller Action Window
  src/controllers/actions/actions.ts
Labels: refactoring

#1480 Mobile&Web: Rewards in stk
  src/hooks/useClaimableWalletToken/useClaimableWalletToken.ts
Labels: enhancement

#1484 Fix/ `signAndBroadcastAccountOp` status stuck at SIGNING on error
  src/controllers/main/main.ts
Labels: bug

#1481 Feature/smart settings
  src/consts/deploy.ts
  src/consts/signAccountOp/errorHandling.ts
  src/controllers/emailVault/emailVault.test.ts
  src/controllers/estimation/estimation.ts
  src/controllers/keystore/keystore.test.ts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/controllers/signMessage/signMessage.test.ts
  src/interfaces/account.ts
  src/interfaces/keystore.ts
  src/libs/7702/7702.ts
  src/libs/account/BaseAccount.ts
  src/libs/account/EOA7702.ts
  src/libs/accountOp/accountOp.ts
  src/libs/accountState/accountState.ts
  src/libs/broadcast/broadcast.ts
  src/libs/keystoreSigner/keystoreSigner.ts
  src/libs/main/main.ts
  src/libs/tracer/debugTraceCall.test.ts
Labels: enhancement

#1487 Support the changes in 7677
  src/libs/erc7677/erc7677.ts
Labels: enhancement

#1485 Fix: no fee found on race conditions
  src/controllers/estimation/estimation.ts
Labels: bug

#1486 Fix: swap&bridge on from token chain change
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug

#1488 Fix: fetch the entry point nonce for EOAs
  contracts/compiled/AmbireAccountState.json
  contracts/deployless/AmbireAccountState.sol
Labels: bug

#1473 Improve / Keystore Encrypt and Decrypt Performance on Firefox
  package-lock.json
  package.json
  src/controllers/accountPicker/accountPicker.test.ts
  src/controllers/emailVault/emailVault.test.ts
  src/controllers/keystore/keystore.test.ts
  src/controllers/keystore/keystore.ts
  src/controllers/main/main.test.ts
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signMessage/signMessage.test.ts
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/interfaces/platform.ts
  src/libs/scrypt/scryptAdapter.ts
  src/libs/signMessage/signMessage.test.ts
Labels: enhancement, refactoring

#1489 Fix / AccountPicker AddAccounts Bug
  src/controllers/accountPicker/accountPicker.ts
Labels: bug

#1494 Allow EOA only txns for 7702 EOAs
  src/libs/account/EOA7702.ts
Labels: enhancement

#1493 Use bundler in 7702 if 0 ETH but receiving ETH and paying in ETH
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/libs/account/BaseAccount.ts
  src/libs/account/EOA7702.ts
  src/libs/estimate/ambireEstimation.ts
Labels: enhancement

#1495 Always return native as a fee option, even if it's empty - for better UX
  src/controllers/estimation/estimation.ts
  src/libs/account/EOA7702.ts
  src/libs/account/V1.ts
  src/libs/account/V2.ts
  src/libs/portfolio/helpers.ts
Labels: bug

#1498 Fix/ Swap and bridge action-window session not cleared
  src/controllers/main/main.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug

#1499 Add: the unichain fee tokens
  src/consts/gasTankFeeTokens.ts
Labels: enhancement

#1500 Fix: remove leading zeros from txn type 4 sign rlp encode
  src/libs/keystoreSigner/keystoreSigner.ts
Labels: bug

#1502 Add: ink fee tokens
  src/consts/gasTankFeeTokens.ts
Labels: enhancement

#1479 Rewards: claim rewards in stkWallet instead of xWallet
  src/controllers/portfolio/portfolio.ts
  src/libs/portfolio/helpers.ts
  src/libs/transfer/userRequest.ts
Labels: enhancement

#1503 Humanizer: minor UX imporvements
  src/libs/humanizer/modules/FallbackHumanizer/fallBackHumanizer.ts
  src/libs/humanizer/modules/FallbackHumanizer/fallbackHumanizer.test.ts
  src/libs/humanizer/modules/Uniswap/uniUniversalRouter.ts
  src/libs/humanizer/modules/Uniswap/uniV3.ts
  src/libs/humanizer/modules/WALLET/index.ts
  src/libs/humanizer/modules/Wrapping/wrapping.ts
  src/libs/humanizer/utils.ts
Labels: enhancement

#1504 Do not call the gas price of the bundler if it's not supported on the chain
  src/controllers/gasPrice/gasPrice.ts
Labels: bug

#1506 fix(humanizer): revoke approve on pancake
  src/libs/humanizer/modules/Pancake/index.ts
Labels: bug

#1508 Add: humanize insufficient amount & quote expired
  src/libs/errorHumanizer/errors.ts
  src/libs/errorHumanizer/estimationErrorHumanizer.ts
Labels: enhancement
