Repository AmbireTech/ambire-common, pull requests merged in 2025-02, with the labels that each got.

#1263 Fix/ isOffline is set to true incorrectly
  src/controllers/main/main.ts
  src/libs/selectedAccount/selectedAccount.ts
Labels: bug

#1276 Bug/ Relayer error handler swallows error reasons
  src/libs/errorDecoder/errorDecoder.test.ts
  src/libs/errorDecoder/handlers/relayer.ts
  src/libs/errorHumanizer/broadcastErrorhumanizer.test.ts
  src/libs/errorHumanizer/errors.ts
Labels: bug

#1274 Refactoring / Swap & Bridge Form Reset on Submit
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/libs/swapAndBridge/swapAndBridge.ts
Labels: refactoring

#1273 Fix / Price request - Missing network
  src/controllers/defiPositions/defiPositions.ts
  src/libs/portfolio/gecko.ts
Labels: bug

#1130 Fix/ Pinned Tokens Not Passed to Portfolio lib on failed RPC
  src/controllers/portfolio/portfolio.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/libs/banners/banners.ts
  src/libs/portfolio/getNetworksWithAssets.ts
  src/libs/portfolio/interfaces.ts
  src/libs/selectedAccount/errors.ts
Labels: bug

#1291 Refactoring / ActionsController Tests
  src/controllers/actions/actions.test.ts
  src/controllers/actions/actions.ts
Labels: refactoring

#1285 Feature / Seed Passphrase
  src/controllers/accountAdder/accountAdder.test.ts
  src/controllers/keystore/keystore.test.ts
  src/controllers/keystore/keystore.ts
  src/interfaces/keystore.ts
  src/libs/keyIterator/keyIterator.test.ts
  src/libs/keyIterator/keyIterator.ts
  src/libs/keystoreSigner/keystoreSigner.test.ts
Labels: enhancement

#1289 Selected account portfolio defi fixes
  src/controllers/defiPositions/defiPositions.ts
  src/controllers/main/main.ts
  src/controllers/selectedAccount/selectedAccount.ts
  src/libs/selectedAccount/selectedAccount.ts
Labels: bug

#1300 Remove ethereumjs-abi and js-sha3 libs
  package-lock.json
  package.json
  src/libs/proxyDeploy/deploy.ts
  src/services/bundlers/bundler.ts
  src/utils/simulationStateOverride.ts
  test/AmbireAccount/BasicTest.ts
Labels: enhancement

#1308 Enhancement/ UI error implementation to swapAndBridge
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: enhancement

#1310 Update/ Swap ctrl to fallback to cache token list and add portfolio tokens on error
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/services/socket/api.ts
Labels: enhancement

#1280 Humanizer: legends humanizer claim xp for survey and socket cases
  src/libs/humanizer/const/abis/Legends.ts
  src/libs/humanizer/const/abis/socket.ts
  src/libs/humanizer/modules/Legends/index.ts
  src/libs/humanizer/modules/Socket/socketModules.ts
Labels: enhancement

#1317 UX/ Benzin display actual txn fee
  src/libs/calls/calls.ts
  src/libs/humanizer/utils.ts
  src/services/assetInfo/assetInfo.ts
Labels: enhancement

#1316 Fix / Always Pending Active Route due to a Failed Transaction
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug

#1295 Feature / Keystore Extra Entropy
  src/controllers/keystore/keystore.ts
  src/libs/entropyGenerator/entropyGenerator.test.ts
  src/libs/entropyGenerator/entropyGenerator.ts
Labels: enhancement

#1320 Humanizer: update texts for fallback humanization
  src/libs/humanizer/index.test.ts
  src/libs/humanizer/modules/FallbackHumanizer/fallBackHumanizer.ts
Labels: enhancement

#1323 Bug/ Current action not reset on removeAction (actions ctrl)
  src/controllers/actions/actions.ts
Labels: bug

#1326 Bug/ Switch account action not working
  src/controllers/actions/actions.ts
  src/controllers/main/main.ts
  src/libs/main/main.ts
Labels: bug

#1324 Feature / Phishing Detection Controller
  package-lock.json
  package.json
  src/controllers/main/main.ts
  src/controllers/phishing/phishing.test.ts
  src/controllers/phishing/phishing.ts
  src/interfaces/dapp.ts
Labels: enhancement

#1329 Bug/ Flashing offline banner
  src/controllers/main/main.ts
Labels: bug

#1335 Humanizer: withdraw and rage leave should humanize xWALLET not WALLET
  src/libs/humanizer/modules/WALLET/stakingPools.ts
  src/libs/humanizer/modules/WALLET/wallet.test.ts
Labels: bug

#1332 Bug/ ERC20 gas estimation on networks with really low fees
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#1328 Bug/ portfolio `PriceFetchError` is never displayed
  src/controllers/portfolio/portfolio.ts
Labels: bug

#1336 Add token name to structure
  contracts/compiled/BalanceGetter.json
  contracts/compiled/DeFiAAVEPosition.json
  contracts/compiled/DeFiUniswapV3Positions.json
  contracts/compiled/IERC20.json
  contracts/deployless/BalanceGetter.sol
  contracts/deployless/DeFiAAVEPosition.sol
  contracts/deployless/DeFiUniswapV3Positions.sol
  contracts/deployless/IERC20.sol
  src/consts/networks.ts
  src/controllers/networks/networks.test.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/interfaces/network.ts
  src/libs/defiPositions/providers/aaveV3.ts
  src/libs/defiPositions/providers/uniV3.ts
  src/libs/defiPositions/types.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimateBundler.test.ts
  src/libs/portfolio/getOnchainBalances.ts
  src/libs/portfolio/helpers.ts
  src/libs/portfolio/interfaces.ts
  src/libs/portfolio/portfolio.ts
  src/libs/selectedAccount/selectedAccount.ts
  src/libs/signMessage/signMessage.test.ts
  src/services/bundlers/bundler.test.ts
  src/utils/networks.ts
Labels: enhancement
