Repository AmbireTech/ambire-common, pull requests merged in 2025-10, with the labels that each got.

#1810 Change / DeFi deposit label to deposit pool
  src/controllers/defiPositions/defiPositions.ts
Labels: bug

#1813 Fix / ContractNamesController infinite loop
  src/controllers/contractNames/contractNames.ts
  src/controllers/main/main.ts
Labels: bug, refactoring

#1821 Rewards func for calcing rewards now has minimum lvl and balance
  src/utils/rewards.ts
Labels: enhancement

#1827 Add: candide config without enabling them
  src/services/bundlers/candide.ts
Labels: configuration

#1830 Rewards: change apy formulla
  src/utils/rewards.ts
Labels: enhancement

#1828 Feature/ Supplement account learned token hints with hints from other accounts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
Labels: enhancement
