Repository AmbireTech/ambire-common, pull requests merged in 2025-03, with the labels that each got.

#1334 Sign Message: allow v1 accs to sign anything if OG mode is activated
  src/controllers/main/main.ts
  src/controllers/signMessage/signMessage.ts
  src/libs/signMessage/signMessage.test.ts
  src/libs/signMessage/signMessage.ts
Labels: enhancement

#1339 Bug/ Offline banner flashing and #getAdditionalPortfolio not awaited
  src/controllers/main/main.ts
  src/controllers/portfolio/portfolio.ts
Labels: bug

#1333 Enhancement / Group Swap&Bridge Banners For In-progress and Complete
  src/interfaces/banner.ts
  src/libs/banners/banners.ts
Labels: enhancement

#1347 Rich json: add options for indentations for stringifying
  src/libs/humanizer/modules/OpenSea/index.ts
  src/libs/richJson/richJson.ts
Labels: enhancement

#1350 Feature/7702 sepolia
  hardhat.config.ts
  src/consts/7702.ts
  src/consts/deploy.ts
  src/utils/networks.ts
Labels: enhancement

#1345 Refactor: resolve feedback for og mode signing in v1
  src/controllers/main/main.ts
  src/controllers/signMessage/signMessage.test.ts
  src/controllers/signMessage/signMessage.ts
  src/libs/signMessage/signMessage.ts
Labels: refactoring

#1354 Humanizer: humanizer ascii module incorrectly assumed plaintext in call.data
  src/libs/humanizer/modules/AsciiModule/asciiModule.ts
Labels: bug

#1170 Refactor/ Add `fetchWithTimeout` and use it in portfolio's batcher
  src/libs/portfolio/batcher.ts
  src/utils/fetch.ts
Labels: refactoring

#1341 Feature / Recover Lost Connection with Dapps
  src/classes/session.ts
  src/controllers/dapps/dapps.ts
  src/controllers/main/main.ts
Labels: enhancement

#1356 Config / Additional Networks Optimizations
  src/controllers/networks/networks.ts
  src/interfaces/network.ts
  src/libs/networks/networks.ts
  src/utils/networks.ts
Labels: refactoring

#1360 Fix: estimation nonce for estimateGas() was incorrect
  src/interfaces/account.ts
  src/libs/accountState/accountState.ts
  src/libs/estimate/providerEstimateGas.ts
  src/libs/tracer/debugTraceCall.test.ts
Labels: bug

#1361 If there's no bundler on a custom network, mark is as smart accounts not supported
  src/libs/account/EOA7702.ts
  src/libs/account/V2.ts
  src/libs/networks/networks.ts
Labels: bug

#1362 fix: chain id on paymaster service discrepancy
  src/libs/erc7677/erc7677.ts
Labels: bug

#1363 Fix: estimate gas pending
  src/libs/broadcast/broadcast.ts
Labels: bug

#1364 Use the pending block for provider estimation as well
  src/libs/estimate/providerEstimateGas.ts
Labels: bug

#1365 Fix: prioritize gas tank for fee call
  src/libs/estimate/estimateHelpers.ts
  src/libs/paymaster/paymaster.ts
Labels: bug

#1369 Fix: token discovery for EOAs
  src/libs/tracer/debugTraceCall.ts
Labels: bug

#1370 Add: new 7702 contracts
  contracts/compiled/AmbireAccount7702.json
  src/consts/7702.ts
  src/consts/deploy.ts
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#1375 Bug/ Portfolio loading states not updated during simulation (selectedAccount)
  src/controllers/selectedAccount/selectedAccount.ts
Labels: bug

#1372 Bug/ `Cannot read property of undefined .toLowerCase()` during error humanization
  src/libs/errorDecoder/handlers/biconomy.ts
  src/libs/errorDecoder/handlers/pimlico.ts
  src/libs/errorHumanizer/humanizeCommonCases.ts
Labels: bug

#1366 Feature / Storage Controller
  src/controllers/accountAdder/accountAdder.test.ts
  src/controllers/accounts/accounts.test.ts
  src/controllers/accounts/accounts.ts
  src/controllers/actions/actions.test.ts
  src/controllers/activity/activity.test.ts
  src/controllers/activity/activity.ts
  src/controllers/addressBook/addressBook.test.ts
  src/controllers/addressBook/addressBook.ts
  src/controllers/dapps/dapps.ts
  src/controllers/defiPositions/defiPositions.test.ts
  src/controllers/emailVault/emailVault.test.ts
  src/controllers/emailVault/emailVault.ts
  src/controllers/invite/invite.ts
  src/controllers/keystore/keystore.test.ts
  src/controllers/keystore/keystore.ts
  src/controllers/main/main.ts
  src/controllers/networks/networks.test.ts
  src/controllers/networks/networks.ts
  src/controllers/phishing/phishing.test.ts
  src/controllers/phishing/phishing.ts
  src/controllers/portfolio/portfolio.test.ts
  src/controllers/portfolio/portfolio.ts
  src/controllers/selectedAccount/selectedAccount.test.ts
  src/controllers/selectedAccount/selectedAccount.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signMessage/signMessage.test.ts
  src/controllers/storage/storage.test.ts
  src/controllers/storage/storage.ts
  src/controllers/swapAndBridge/swapAndBridge.test.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/controllers/transfer/transfer.test.ts
  src/interfaces/network.ts
  src/interfaces/storage.ts
  src/libs/account/account.ts
  src/libs/humanizer/index.ts
  src/libs/keys/keys.ts
  src/libs/main/main.ts
  src/libs/networks/networks.ts
  src/libs/portfolio/migrations/tokenPreferences.test.ts
  src/libs/portfolio/migrations/tokenPreferences.ts
  src/libs/selectedAccount/selectedAccount.ts
  src/libs/signMessage/signMessage.test.ts
  src/libs/storage/storage.ts
  test/helpers.ts
Labels: enhancement, refactoring

#1380 Enable 7702 on BNB
  src/consts/gasTankFeeTokens.ts
  src/consts/networks.ts
  src/libs/account/BaseAccount.ts
  src/libs/account/EOA.ts
  src/libs/account/EOA7702.ts
  src/libs/account/V1.ts
  src/libs/account/V2.ts
  src/libs/estimate/ambireEstimation.ts
  src/libs/estimate/estimate.ts
Labels: bug, enhancement, configuration

#1381 Include additionalCallData in gasUsed
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/account/BaseAccount.ts
  src/libs/account/EOA.ts
  src/libs/account/EOA7702.ts
  src/libs/account/V1.ts
  src/libs/account/V2.ts
  src/libs/gasPrice/gasPrice.ts
Labels: bug, enhancement

#1385 Add: 7702 activator gas
  src/controllers/signAccountOp/signAccountOp.ts
  src/libs/account/EOA7702.ts
Labels: bug

#1386 Fix: gasUsed calc for each option
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#1383 Bug/ `identifiedBy` is missing in really old account ops
  src/controllers/activity/activity.ts
  src/libs/accountOp/submittedAccountOp.ts
Labels: bug

#1379 Fix: debug_traceCall fails on every first call on each network
  src/controllers/main/main.ts
  src/libs/tracer/debugTraceCall.test.ts
  src/libs/tracer/debugTraceCall.ts
Labels: bug

#1394 Add support for sonic mainnet
  src/services/bundlers/bundler.ts
  src/services/bundlers/getBundler.ts
Labels: enhancement

#1395 Declare estimation errors only if the account types say they are fatal
  src/libs/account/BaseAccount.ts
  src/libs/account/EOA.ts
  src/libs/estimate/callGasUsedEstimation.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.ts
  src/libs/estimate/estimateEOA.ts
  src/libs/estimate/estimateWithRetries.ts
Labels: bug

#1397 Fix/ EOA batching has no simulation
  src/controllers/main/main.ts
  src/libs/main/main.ts
Labels: bug
