Repository AmbireTech/ambire-common, pull requests merged in 2025-08, with the labels that each got.

#1646 Fix: #abortHWTransactionSign logic
  src/controllers/main/main.ts
Labels: bug

#1647 Fix: disabled network crash in activity banner
  src/controllers/activity/activity.ts
Labels: bug

#1650 Allow build in swap retry on hw
  src/controllers/main/main.ts
Labels: bug

#1656 Cut off bundler gas failures
  src/controllers/gasPrice/gasPrice.ts
  src/libs/estimate/estimateBundler.ts
Labels: enhancement

#1673 Use original bundler gas price
  src/controllers/signAccountOp/signAccountOp.ts
  src/services/bundlers/biconomy.ts
  src/services/bundlers/bundler.ts
  src/services/bundlers/gelato.ts
  src/services/bundlers/pimlico.ts
Labels: enhancement

#1678 Add: a better error humanizer for a custom slippage error message
  src/libs/errorHumanizer/errors.ts
Labels: enhancement

#1632 Fix / Swap & Bridge - Retry
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug

#1682 Fix: increased bundler gas prices for v2 accounts as well
  src/controllers/signAccountOp/signAccountOp.ts
Labels: bug

#1683 Fix: invalid account nonce trigger
  src/libs/estimate/estimateBundler.ts
Labels: bug

#1684 Better EOA error handling
  src/libs/account/EOA.ts
  src/libs/account/EOA7702.ts
Labels: enhancement

#1695 Fix/ Execution failed error (undefined provider)
  src/controllers/selectedAccount/selectedAccount.ts
  src/libs/selectedAccount/errors.ts
Labels: bug

#1705 Feature/encrypted json export
  src/controllers/keystore/keystore.ts
Labels: enhancement

#1712 Fix: the etherspot bundler integration was missing a function
  src/services/bundlers/etherspot.ts
Labels: bug

#1711 User op nonce check optimizations
  src/controllers/estimation/estimation.ts
  src/controllers/main/main.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/signAccountOp/signAccountOp.ts
  src/controllers/signAccountOp/signAccountOpTester.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/controllers/transfer/transfer.ts
  src/libs/estimate/estimate.ts
  src/libs/estimate/estimateBundler.ts
Labels: enhancement

#1717 Feature/candide
  src/consts/bundlers.ts
  src/services/bundlers/bundler.ts
  src/services/bundlers/candide.ts
  src/services/bundlers/getBundler.ts
Labels: enhancement

#1730 Change insufficient gas message to insufficient {native} as gas is a bit confussing
  src/libs/errorDecoder/errorDecoder.test.ts
  src/libs/errorHumanizer/errors.ts
  src/libs/estimate/estimate.test.ts
Labels: bug

#1719 Feature: Gas Limit on Estimation.sol
  contracts/compiled/Estimation.json
  contracts/deployless/Estimation.sol
  contracts/deployless/EstimationStructs.sol
  contracts/deployless/FeeTokens.sol
  contracts/deployless/SimulateSigned.sol
  contracts/testHelpers/GasGuard.sol
  scripts/deployGasGuard.js
  src/controllers/actions/actions.test.ts
  src/controllers/signAccountOp/signAccountOp.test.ts
  src/controllers/swapAndBridge/swapAndBridge.ts
  src/controllers/transfer/transfer.ts
  src/libs/accountOp/accountOp.test.ts
  src/libs/accountOp/accountOp.ts
  src/libs/estimate/ambireEstimation.ts
  src/libs/estimate/estimate.test.ts
  src/libs/estimate/estimateBundler.test.ts
  src/libs/estimate/interfaces.ts
  src/libs/humanizer/humanizerModules.test.ts
  src/libs/humanizer/index.test.ts
  src/libs/humanizer/modules/1Inch/1inch.test.ts
  src/libs/humanizer/modules/Aave/aave.test.ts
  src/libs/humanizer/modules/Across/across.test.ts
  src/libs/humanizer/modules/AsciiModule/asciiModule.test.ts
  src/libs/humanizer/modules/Curve/curve.test.ts
  src/libs/humanizer/modules/FallbackHumanizer/fallbackHumanizer.test.ts
  src/libs/humanizer/modules/Guild/Guild.test.ts
  src/libs/humanizer/modules/KyberSwap/kyberSwap.test.ts
  src/libs/humanizer/modules/Lido/lido.test.ts
  src/libs/humanizer/modules/Lifi/lifi.test.ts
  src/libs/humanizer/modules/Pancake/Pancake.test.ts
  src/libs/humanizer/modules/Privileges/privileges.test.ts
  src/libs/humanizer/modules/Socket/socket.test.ts
  src/libs/humanizer/modules/Sushiswap/sushiswap.test.ts
  src/libs/humanizer/modules/Tokens/tokens.test.ts
  src/libs/humanizer/modules/TraderJoe/traderjoe.test.ts
  src/libs/humanizer/modules/Uniswap/uniswap.test.ts
  src/libs/humanizer/modules/WALLET/wallet.test.ts
  src/libs/humanizer/modules/Wrapping/wrapping.test.ts
  src/libs/portfolio/portfolio.test.ts
  src/libs/requests/requests.ts
  src/libs/selectedAccount/selectedAccount.test.ts
  src/libs/tracer/debugTraceCall.test.ts
  src/libs/userOperation/userOperation.test.ts
  src/services/bundlers/bundler.test.ts
Labels: bug, enhancement

#1731 Add 10% gas limit overhead on EOAs
  src/libs/account/EOA.ts
  src/libs/broadcast/broadcast.ts
Labels: bug

#1732 Feature/no routes found retry
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: enhancement

#1737 Swap&bridge better slippage
  src/services/lifi/api.ts
Labels: bug

#1738 Disable auto route selection on proceeding
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug

#1739 Invalid account nonce on ethereum, retry once
  src/libs/estimate/estimateBundler.ts
Labels: bug
