Repository AmbireTech/ambire-common, pull requests merged in 2025-09, with the labels that each got.

#1744 Estimation.sol better namings for binary search mechanism
  contracts/compiled/Estimation.json
  contracts/deployless/Estimation.sol
  contracts/deployless/EstimationStructs.sol
  contracts/deployless/SimulateSigned.sol
Labels: enhancement

#1743 Reset the this.isAutoSelectRouteDisabled flag on setUserProceeded
  src/controllers/swapAndBridge/swapAndBridge.ts
Labels: bug

#1745 Estimation.sol - failure on gasLimit > block.gasLimit
  contracts/compiled/Estimation.json
  contracts/deployless/Estimation.sol
  src/libs/account/EOA.ts
  src/libs/errorHumanizer/helpers.ts
  src/libs/estimate/estimate.test.ts
Labels: bug, enhancement

#1754 Fixes / ContinuousUpdatesController tests
  src/classes/recurringTimeout/recurringTimeout.ts
  src/controllers/accounts/accounts.ts
  src/controllers/continuousUpdates/continuousUpdates.test.ts
  src/controllers/continuousUpdates/continuousUpdates.ts
  test/recurringTimeout.ts
Labels: bug

#1757 Hotfix/ SelectedAccount infinite loading and minor type errors
  src/controllers/selectedAccount/selectedAccount.ts
  src/libs/selectedAccount/errors.ts
  src/libs/selectedAccount/selectedAccount.ts
Labels: bug

#1762 Fix / AccountPicker used on networks logic issues
  src/controllers/accountPicker/accountPicker.ts
Labels: bug, refactoring

#1767 Humanizer: nft approval humanization
  src/libs/humanizer/modules/Tokens/tokens.ts
Labels: enhancement

#1779 Humanizer: use desired amount instead of min for providding liquidity
  src/libs/humanizer/modules/Uniswap/uniV3.ts
  src/libs/humanizer/modules/Uniswap/uniswap.test.ts
Labels: enhancement

#1780 Fix / Missing DeFi positions and incorrect total balance when the extension is offline
  src/controllers/defiPositions/defiPositions.ts
Labels: bug

#1788 Enable candide on celo
  src/services/bundlers/candide.ts
Labels: enhancement

#1784 Refactoring / Pending Transactions Visualization
  src/controllers/activity/activity.test.ts
  src/controllers/activity/activity.ts
  src/controllers/main/main.ts
  src/interfaces/banner.ts
  src/libs/banners/banners.ts
Labels: refactoring

#1798 Fix / Wallet Connect EIP-6963 connection
  src/classes/session.ts
  src/controllers/dapps/dapps.ts
Labels: bug

#1791 Humanizer: bitrefill for rewards
  src/libs/humanizer/const/abis/Legends.ts
  src/libs/humanizer/modules/Legends/index.ts
Labels: enhancement

#1804 Humanizer: fix typo
  src/libs/humanizer/modules/Uniswap/uniV2.ts
Labels: enhancement
